### ISSUE TITLE
CLI HandleResponse should allow pure JSON output

### ISSUE THREAD

**Issue by mark-lb** [goadesign/goa#1002]
Currently, HandleResponse only tries to print pure JSON in the case of 2xx status responses.
It should try to do the same also in the case of other HTTP status responses, of course also enabling the pretty print option. Currently, error responses just get the body printed as a string.
Additionally, if it succeeded in JSON unmarshalling the body for a bad status, we can safely assume that there is no reason to print "error: statusCode", which should only be printed when unmarshaling failed.

**Comment by raphael** [comment]
Makes sense, I guess the difference with 2xx is that the code should not report an unmarshal error but instead print the original error like it does now. This is because in general there is no guarantee that error responses are correctly encoded (e.g. internal errors). Also really the code shouldn't assume JSON - it should use the client decoder instead.
