### ISSUE TITLE
[Proposal] Allow zero value for a required string attribute.

### ISSUE THREAD

**Issue by brycereitano** [goadesign/goa#1009]
### Proposal
I propose that there should a method of allowing the zero value for a required `String` attribute.

#### Option 1
Remove the default generated validation, that of which validates that the string is non-empty. If you need to validate that the string is non-empty use the `Minimum` validation.

This however could cause some unintended behaviour for existing applications.

#### Option 2
Add an "AllowBlank" to the attribute design. This would just tell the generator to not generate the validation. Other validations will still be generated for that attribute. Even if there is a `Minimum` validation, which could cause some confusion in the design.
```go
MediaType("application/vnd.foo+json", func() {
  Attribute("description", String, "Description of the foo object.", func() {
    AllowBlank(true)
  })
})
```

### Problem
If the an attribute in the design is required, it will validate that the string is non-empty. If it is empty, it will add a validation error stating that the value is missing.
```go
MediaType("application/vnd.foo+json", func() {
  Attribute("description", String, "Description of the foo object.")
  Required("description")
})
```

When not requiring the parameter optional, that validation is not generated. In addition, this automatically adds `omitempty` tags to the structs. This also allows nil values, which in my use-case is not desired.

One technical boundry, we could run up against is whether we can represent this well in "OpenAPI" (Swagger) and "JSON Schema".

### Use-Case
There is no concrete use-case that I have that makes this an objective decision. However, as I design out an API. I would like to enforce that an attribute will be provided *some* concrete value in the request/response body. With that, the server and client can assume the value they get is *the* value desired.

**Comment by raphael** [comment]
**Option 1** seems the most attractive to me. The risk is that controller code may rely on the value not being empty so we'd have to document the change carefully (Basically you'd have to add a `MinLength(1)` validation to get the same behavior). However it wouldn't completely break existing code since it allows more so it should be OK to change in a minor revision.

One drawback is that all the encoders/decoders need to make sure to "carry" empty strings properly. This is the reason that today a required string cannot be empty. In practice this works fine with JSON given the tags generated by goa (i.e. no `omitempty` tag for required attributes).
