### ISSUE TITLE
benchmark?

### ISSUE THREAD

**Issue by cocodrino** [goadesign/goa#1057]
Hi guys, I'm courious about the performance, is there any benchmark or doc about the performance?..how is it compared to microframeworks like gorilla o echo?..thank you!!.

**Comment by raphael** [comment]
There is no benchmark published because the truth of the matter is that the bottleneck is not going to be goa (or echo or gorilla or ...), it's going to be the actual app code, database, dependent services etc.
That being said you can see some benchmarks being run in Brian's goa video: https://www.youtube.com/embed/tCFrgWikEX8
