### ISSUE TITLE
Add a `Bytes` Primitive Type to Goa `v1`

### ISSUE THREAD

**Issue by JKhawaja** [goadesign/goa#1075]
A Goa primitive type that maps to a `[]byte` in Go and possibly JSON objects in other places (e.g. swagger) could be a useful. It is upcoming in Goa `v2`, however a `v1` update with it could be useful (and simpler/faster to implement). Any thoughts or questions?

**Comment by raphael** [comment]
Thanks for opening the issue! Just to be clear, adding a new primitive type requires updating all the code generators (`genapp`, `gen_client`, `gen_controller`, `gen_js`, `gen_main`, `gen_schema` and `gen_swagger`). In most cases I expect the required changes to be small though.

**Comment by JKhawaja** [comment]
Will there be any other reason for a `Bytes` primitive to exist other than it mapping to a `json.RawMessage` type in the `gen_app` code? Which would imply that it is only useful when using either JSON encoding for producing or consuming.

**Comment by raphael** [comment]
I think a `Byte` type would have many more applications. The question though is not what it would be used for, it's what needs to be done so that goagen isn't broken if someone uses `Byte` in the design. Also it wouldn't map to `json.RawMessage` but to `[]byte` in the generated code, that code has to be independent of encoding. (the controller can then simply type assert to `json.RawMessage`).

**Comment by JKhawaja** [comment]
Will the goa JSON encoder unmarshal the request Payload to a Type definition if a field has a Type `[]byte` or a `*[]byte`? I don't think it will. That is why I am wondering if there are any specific use cases for typing an `Attribute` as `Byte`. Outside of request and response body types it does not seem like too many people would care about arrays of uint8s?

**Comment by raphael** [comment]
The broader use case for bytes is just plain binary data rather than a valid set of UTF-8 characters. You're right that the default JSON behavior today will be to do the base 64 encode/decode which is not great. We can't use `json.RawMessage` as the Go type for `Byte` though, again it needs to be a type that works with any marshaler / Swagger / JavaScript etc. Primitive types that are defined in the DSL cannot be bound to a specific code generator / output. 

Maybe a solution here would be to add a special Metadata tag that allows overriding the type generated for the `app` package. This would be useful for other things as well (e.g. `int64` instead of `int`).

**Comment by JKhawaja** [comment]
So, would it be a `struct:field:type` tag that gets called like `Metadata("struct:field:type", "json.RawMessage")`?

**Comment by raphael** [comment]
Yes exactly. I'm not sure `goagen` needs to validate anything. It should just blindly use the given type instead of the one it would use - it is the responsibility of the user to make sure it's compatible. Maybe that's all you need for your use case actually now that I think about it :)

**Comment by JKhawaja** [comment]
Yes agree on no validation. And, that is true that a `Metadata()` field Type converter would work for my use case as well. 

So, would you like to move this enhancement that direction rather than implementing a new primitive? The interesting thing is that this `Metadata()` converter would work on any primitive, but there would still need to be a list of allowed Types per Goa Primitive Type that it can blindly convert too. Perhaps, we can instead come up with those lists and implement that?

**Comment by raphael** [comment]
I don't understand this part:
>but there would still need to be a list of allowed Types per Goa Primitive Type 
Since we shouldn't validate anyway why do we need a list of allowed types?

**Comment by JKhawaja** [comment]
Well if I use type `String` for my `Attribute` and I use a `struct:field:type` metadata tag, I can't just arbitrarily put anything for the value: `Metadata("struct:field:type", "arbitraryThing")`? Right?

**Comment by raphael** [comment]
haha yes that's what I meant. We can't predict all the possible use cases and it will fail pretty clearly anyway if something is used that doesn't work.

**Comment by JKhawaja** [comment]
I think that a Metadata tag enhancement is more appropriate for Goa `v1` anyways. I think that increasing the number of Primitive types seems more of something for `v2` moving forward. 

So, I will focus a PR around the new Metadata tag: `struct:field:type`, which will also allow `v1` users to use `[]byte` as a field Type in their generated Go code.

**Comment by raphael** [comment]
Sounds good, thank you for the back and forth and sorry for the extra work...

**Comment by JKhawaja** [comment]
So, the new Metadata tag works. Code and Tests are written. The only issue now is that the generated code will not add the appropriate packages for the specified Type. For example, using `Metadata("struct:field:type", "json.RawMessage")` will not actually import the `encoding/json` package in the generated code. :( 

So, that is OKAY, but it forces the user to have to manually update the generated code with an import  if their Type is not a built-in Go type.

**Comment by raphael** [comment]
Yeah I was thinking about that too. There is code in goagen that will remove extra imports but it won't add missing imports on purpose because it's not guaranteed that goimports always picks up the right package.
Instead of adding a new metadata we could tweak the `struct:field:type` metadata so that it can optionally specify a package in a second optional argument:
```go
Metadata("struct:field:type", "json.RawMessage", "encoding/json")
```
This seems a bit better because there is no use for a `import` metadata otherwise.

**Comment by JKhawaja** [comment]
Yeah, adding a third argument to the `struct:field:type` tag does seem like it should do the job. Should we do that in a different PR?

**Comment by raphael** [comment]
Might as well just add to the one that's already opened, thank you!
