### ISSUE TITLE
goagen bootstrap can lead to data loss

### ISSUE THREAD

**Issue by jgillich** [goadesign/goa#1086]
I wanted to try out goa, so I made a new subfolder in my project and ran:

```
goagen bootstrap -d project/api/design
```

Since the `design` folder is in a subfolder, I expected it to put the generated files in the same folder. Nope, it fully replaced the folders in my project root, where `app/` was a frontend JavaScript application. Thank god I use git, so nothing major was lost, but this is extremely dangerous.

I think there should really be some kind of safety check here, like reading `app/controllers.go` and checking for the `Code generated by goagen` comment, and if that fails, make the user confirm the action.

**Comment by raphael** [comment]
Thanks for the report. It's a little bit more complicated :)

As described [here](https://goa.design/implement/goagen/) `goagen` generates two kinds of output:

* The scaffold which is generated only once and that `goagen` will not override, this is the `main` package for the server and for the client. `goagen main` does not override any file if it already exists (`goagen bootstrap` runs `goagen main` as well as `goagen app`, `goagen client` and `goagen swagger` as described below).

* The generated code which is everything else - in particular the server code which is by default the `app` package (can be changed with `--pkg`). The generated code is always regenerated entirely each time and should never be modified.

So the fact that `goagen` re-generates the `app` directory each time is by design, it is unfortunate that the name is such a common word. I guess the tool could make sure that the directory only contains files that were previously generated by `goagen`. I'll leave this issue opened as an enhancement to do that.
