### ISSUE TITLE
Multiple errors response

### ISSUE THREAD

**Issue by tpoxa** [goadesign/goa#1173]
Hello. For server side validation my client needs to have response like this.

HTTP CODE 422

JSON
```
[
{"field":"name", "error":"Field is required"},
{"field":"email", "error":"Field is required"},
]
```
How to implement this with goa.design?

Thank you

**Comment by raphael** [comment]
You can replace the `ErrInvalidRequest` with your own error class that produces the format you want. However when multiple errors are produced `MergeErrors` produces a `500` in this case because it doesn't know about any other error type than `ErrorResponse` which is probably not what you want. This is a common request so I would gladly accept a PR that tweaks `MergeErrors` so it works with custom error types as well.
