### ISSUE TITLE
A proposal: Do gofmt generated by goa

### ISSUE THREAD

**Issue by tikasan** [goadesign/goa#1180]
I do not know whether it is technically possible, but I'd like to gofmt the code created by goa, but do you think that this is necessary as the production side?

**Comment by raphael** [comment]
This is already done here: https://github.com/goadesign/goa/blob/master/goagen/codegen/workspace.go#L250 Did you see generated code that wasn't properly formatted?

**Comment by tikasan** [comment]
Since I am managing the package with glide, it seems that the version I was using did not correspond.

https://github.com/goadesign/goa/releases/tag/v1.1.0

**Comment by raphael** [comment]
`v1.1.0` also formats the code: https://github.com/goadesign/goa/blob/v1.1.0/goagen/codegen/workspace.go#L250 . This has been there since the very beginning. Are you seeing something that is not formatted or just assuming?

**Comment by tikasan** [comment]
It is not an assumption but an actual event.
It may be goimports instead of gofmt.
The import order is changed when you run goimports.

**Comment by raphael** [comment]
We cannot use `goimports` because it may be adding imports that are not correct. Instead the code uses the Go parser package to remove extra imports. However @moorereason had opened an issue with the Go team so that we could use the `goimports` package by making it possible to format only, see https://github.com/golang/go/issues/14500. This issue was actually addressed so we could take advantage of the `FormatOnly` flag to format the code.

**Comment by tikasan** [comment]
I see. Thank you for providing detailed information!
