### ISSUE TITLE
Codegen: Service main

### ISSUE THREAD

**Issue by tchssk** [goadesign/goa#1203]
https://github.com/goadesign/goa/blob/v2/examples/account/cmd/basic/main.go

**Comment by tchssk** [comment]
Should we implement this at https://github.com/goadesign/goa/blob/v2/codegen/files/rest/server_scaffold.go? @raphael

**Comment by raphael** [comment]
Thank you for asking! I'm not sure anymore :)

The branch where I'm doing work is `encoding_redux`. I'm wondering whether to generate a main at all or at least whether that should be a separate plugin. There is a lot of confusion around the `bootstrap` command with `goagen` because it generates both scaffold (`main.go`, controllers) and non-scaffold code (`app` package). In my latest changes I've changed the `goagen` tool so that:
1. It's called `goa` (that way you can use the v1 and v2 tools without having to re-install each time)
2. It only has one generation command: `gen` which replaces `client`. `server` and `openapi` (so you invoke it with `goa gen <design package>`)
3. It does not generate scaffold code - only the `gen` package.

I'm currently focusing on the client code generation but the server code generation is pretty much done.

If you have some time and would like to help a "fun" topic that still needs to be tackled is how to do plugins. I'm wondering if they can be done by simply adding an import statement to the design and have the imported package (the plugin implementation) add DSL (if needed), register the design root (again if needed) and contain the code generation logic (similiar to what `gen` generates: https://github.com/goadesign/goa/blob/encoding_redux/cmd/goa/gen.go#L237-L292). We could add a phase to the `eval` package `RunDSL` method that looks  whether a root is a `Generator` (implements a `Generate` method) and if so invoke it. Hope that makes sense...

Also would like to know what you think about not generating the scaffold... Thank you!

**Comment by tchssk** [comment]
I agree to call it `goa` and the simple generation. I think scaffolds are not always required but existing goa users will expect them.

**Comment by raphael** [comment]
I ended up implementing a `goa example` command that produces a service and client CLI main as well as empty service methods. See https://github.com/goadesign/goa/blob/v2/codegen/generator/example.go and the resulting files:
* https://github.com/goadesign/goa/blob/v2/examples/cellar/cmd/cellarcli/main.go
* https://github.com/goadesign/goa/blob/v2/examples/cellar/cmd/cellarsvc/main.go
