### ISSUE TITLE
What is the preferred way to auth a user and grant a JWT?

### ISSUE THREAD

**Issue by deltaskelta** [goadesign/goa#1205]
the setup I have now goes like this...

user hits a `BasicAuth` endpoint which creates and signs a JWT which then gets put into the context everytime that the JWT comes in the auth header...

I want to add a relevant user struct to the `"sub"` Claim so I can have access to the users name, email, etc from the JWT... but this leaves me with an issue because as far as I can see, I must pass the user to the `Signin` controller through context (or is there some other way...)

```
// custom type for context key
type contextKey string

// NewAdminBasicAuth is re-implementation of the basic auth that is provided with Goa.
// It takes // what is in the "Authorization" header (grabbed by call to r.BasicAuth)
// and then validates that agains the database
func NewAdminBasicAuth(db *models.AdminDB) goa.Middleware {
	middleware, _ := goa.NewMiddleware(
		func(ctx context.Context, w http.ResponseWriter, r *http.Request) error {
			email, password, ok := r.BasicAuth()
			if !ok || email == "" || password == "" {
				return ErrBasicAuthFailed("Authentication failed, headers not present")
			}

			user, err := db.GetByEmail(ctx, email)
			if err != nil {
				return ErrBasicAuthFailed("Authentication failed: bad user email")
			}

			if password != *user.Password {
				return ErrBasicAuthFailed("Authentication failed: password mismatch")
			}

			// putting the user in the context so it can be put into the JWT when it
			// is created
			var key contextKey = "user"
			ctx = context.WithValue(ctx, key, user)
			fmt.Println("THIS IS THE CONTEXT IN THE BASICAUTHMIDDLEWARE", ctx)
			return nil
		})
	return middleware
}
```
I can see through printing various things that the user is in the context here but it never makes it to the context that is passed to the JWT `Signin` method. I am having a hard time visualizing everything that is going on behind the scenes here so IDK if I am on the right track or not...

Thanks for any help you can give, I will close the issue if this is not the right place to ask this, but I would like to leave it somewhere for others to find

**Comment by raphael** [comment]
The flow described here makes a lot of sense. The problem seems to be that the middleware does not forward the context to the next. Here is a way to do that:
```go
func NewAdminBasicAuth(db *models.AdminDB) goa.Middleware {
	return func(h goa.Handler) goa.Handler {
		return func(ctx context.Context, w http.ResponseWriter, r *http.Request) error {
			// ...
			// SAME AS ABOVE
			// ...
			ctx = context.WithValue(ctx, key, user)

			return h(ctx, w, r)
		}
	}
}
```
A couple of things to note:
1. Using the string `"user"` as key for the context means that code outside of this middleware can overwrite the value which may or may not be a problem. If you want to prevent that then use a private type in the middleware package to initialize the value of the key (and provide a public function that can extract the value from it a la goa `ContextAction` for example).
2. The dabase connection is used in a closure so it needs to be concurrency (goroutine) safe. Also it's not possible to create a new one and give it to the middleware in case of failure. One way around that if it is a problem is to give access to a connection constructor (e.g. a pool) to the middleware code. Obviously there are also performance considerations here.
