### ISSUE TITLE
Make possible hide stack trace in recover middleware

### ISSUE THREAD

**Issue by karantin2020** [goadesign/goa#1231]
Hello.
Recover middleware in goa v1 by default returns stack trace in error response. That is very bad idea in production environment.
So may be it is possible to turn off output stack trace?

**Comment by raphael** [comment]
Yes, don't use it :-) The whole point of the middleware is to send the callstack to clients which may or may not be suitable depending on whether the API is public or not, in production or not etc. If you don't want the callstack in responses then don't mount this middleware. If you want to recover all panics (which is not always a good idea either - some people believe it's better to let the app panic so that it's clear there's a bug) then simply write your own trivial middleware. There's also https://github.com/codeclysm/goa-raygun which might be interesting.
