### ISSUE TITLE
Make possible to configure default mux router

### ISSUE THREAD

**Issue by karantin2020** [goadesign/goa#1236]
Hello.
Goa service.Mux is equal to *goa.mux. It is not a public struct and it has a private field router.
So it is impossible to configure httptreemux.TreeMux by default (change RedirectBehavior, RedirectTrailingSlash and so on).

Now I implement my own structure for service.Mux. Is it possible to make public goa.Mux (struct in mux.go) and to make it's field Router public too?

Thanks.

**Comment by raphael** [comment]
I would like to avoid making these fields public because then it would make the dependency public. Right now it's all nicely hidden behind an interface and allows for easily swapping the router implementation with others. This also  help with libraries that have dependencies on goa: users of these libraries don't have to import the dependency. So TL;DR implementing your own structure for the cases where you need to tweak the underlying router behavior seems to be the lesser evil.
