### ISSUE TITLE
using "TypeName" inside of Type is throwing erroneous error

### ISSUE THREAD

**Issue by dgaedcke** [goadesign/goa#1253]
using "TypeName" inside a Type is throwing erroneous error

erro: "invalid use of TypeName"

workaround is to declare name as 1st argument

**Comment by raphael** [comment]
So looking into it I realized that making this work would actually be a lot of work. Given that the same can be accomplished by simply providing the type name to the `Type` function and that noone has been using this until now it seems the best course of action is to drop the support for the use of `TypeName` in `Type`. I'm pushing a commit that corrects the comment accordingly. Let me know if this causes a problem for you but otherwise I'll close this issue.
