### ISSUE TITLE
goagen generates unbuildable package

### ISSUE THREAD

**Issue by stevecrozz** [goadesign/goa#1266]
I put together a gist with instructions to reproduce this issue:
https://gist.github.com/stevecrozz/63cb64e5217beab99342e4b0aea9551f

When I follow the steps, I get:
```
$ go build
# gist.github.com/63cb64e5217beab99342e4b0aea9551f/client
./user_types.go:20: undefined: myvendorMyproductAnotherThing
```

**Comment by raphael** [comment]
I believe this issue is related to https://github.com/goadesign/goa/issues/831. A workaround would be to make sure that no types have media types as attributes (the reverse is OK).

**Comment by raphael** [comment]
So what's happening here is that the private types used to validate incoming request payloads are only generated for user types and not for media types. This makes sense because media types should not be used to define payloads. Changing this would require a lot of work for something that is not recommended and can be worked around easily by defining a user type and a corresponding media type using "Reference". TL;DR won't fix. Note also that this problem does not exist in v2 where the validation is done differently and does not require the private types in the first place.
