### ISSUE TITLE
Dual Design Packages Causes 'main' Package to be Redeclared 

### ISSUE THREAD

**Issue by kmacmcfarlane** [goadesign/goa#1273]
I have currently split my design files into two directories, one for our mobile app, and one for our web dashboard.

Consequently, I have to run `goagen` twice like this:
```	@echo "main..."
	@goagen main -d bitbucket.org/lockwobr/healthconnect/healthconnect/design/dashboard -o controllers/dashboard
	@echo "app..."
	@goagen app -d bitbucket.org/lockwobr/healthconnect/healthconnect/design/dashboard --pkg=dashboard

	@echo "main..."
	@goagen main -d bitbucket.org/lockwobr/healthconnect/healthconnect/design/app -o controllers/app
	@echo "app..."
	@goagen app -d bitbucket.org/lockwobr/healthconnect/healthconnect/design/app --pkg=apppublic/docs/dashboard
```

1. The `main` `goagen` command doesn't accept a `pkg=dashboard` style of argument to prevent creating more than one `main` package.
2. Additionally, it generates a main.go that I have to comment out the contents of in order to not re-declare the main package.
3. The action methods in the scaffold reference the `app` package, even if the design package is called `dashboard`. For new controllers, this means I have to change this:
`func (c *AlertDefinitionController) Create(ctx *app.CreateAlertDefinitionContext) error {...}`
into this, and import the package path to the dashboard controllers:
`func (c *AlertDefinitionController) Create(ctx *dashboard.CreateAlertDefinitionContext) error {...}`

It's easily solved by changing the package name of new controllers that get generated at first, but it would be a nice enhancement to specify my own package name (or just use the name of the folder when  the design package name is passed as an argument to the `main` command). Being able to separately specify where main.go will be output would solve my second issue.

Let me know if there's some way to avoid this, otherwise consider this issue an enhancement request.

Thanks!

**Comment by raphael** [comment]
Thanks for the feedback! wrt 1 and 2 the `main` generator is really only meant to be used once because the code it generates must always be edited. Is there really something useful coming out of regenerating the main each time? (as an aside I regret having built the scaffold generation as it's causing more confusion that is saving time - at the end of the day a simple starting point example would probably have been better :) ).

3. is different though - given that there is a scaffold generator it does seem like it should be possible to specify the name of the generated app package. Could you please open a separate issue for this? thank you!

**Comment by kmacmcfarlane** [comment]
Created.

**Comment by raphael** [comment]
See https://github.com/goadesign/goa/issues/1275
