### ISSUE TITLE
Should payload  validations specify context as "request" instead of "response"?

### ISSUE THREAD

**Issue by brycereitano** [goadesign/goa#1324]
Currently in V1 the validation messages for a request say response. This seems a bit counter-productive, as it could confuse programmers on the consumption end.

Example generated code:
```golang
// Validate validates the createUserPayload type instance.
func (ut *createUserPayload) Validate() (err error) {
	if ut.DisplayName == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "displayName"))
	}
}
```

**Comment by raphael** [comment]
Implemented a quick fix. It's probably OK to hardcode to "request" because only request types are validated automatically. If the user code calls "Validate" on a type explicitly then the message might not be ideal (i.e. says "request" no matter where the validation is called from) but then it becomes a choice between making the wording helpful in the 90% case v.s making it generic/not helpful but working in all cases.
