### ISSUE TITLE
ArrayOf Element validation code missing

### ISSUE THREAD

**Issue by klauspost** [goadesign/goa#1352]
Thanks for helping with #1347 

However, it seems like no validation code is generated. Using this design:

```Go
package design

import (
	. "github.com/goadesign/goa/design"
	. "github.com/goadesign/goa/design/apidsl"
)

var Names = ArrayOf(String, func() {
	MinLength(2)
	MaxLength(20)
	Pattern("[a-zA-Z]+")
})

var _ = Resource("get", func() {
	Action("get", func() {
		Routing(GET(""))
		Params(func() {
			Param("ids", Names)
		})
	})
})
```

Generates this code:
```
func NewGetGetContext(ctx context.Context, r *http.Request, service *goa.Service) (*GetGetContext, error) {
	[...]
	paramIds := req.Params["ids"]
	if len(paramIds) > 0 {
		params := paramIds
		rctx.Ids = params
	}
	return &rctx, err
}
```

Again, the documentation leads me to believe there would be validation.

**Comment by raphael** [comment]
That makes sense, there is no parent attribute to attach the validations to. I understand it's not intuitive but fixing this is a fair amount of work as it would involve changing how the type system handles arrays. I would be inclined to make this clear in the docs. One workaround would be wrap the definition with a function instead of a literal type:
```go
func Names() {
	ArrayOf(String, func() {
		MinLength(2)
		MaxLength(20)
		Pattern("[a-zA-Z]+")
	})
}
```
which you'd then use with:
```
var _ = Resource("get", func() {
	Action("get", func() {
		Routing(GET(""))
		Params(func() {
			Param("ids", Names())
		})
	})
}
```
