### ISSUE TITLE
DateTime type example value should be quoted in swagger.yaml

### ISSUE THREAD

**Issue by wayneashleyberry** [goadesign/goa#1367]
Given the following design, the example value for the `DateTime` attribute is quoted in the `swagger.json` output, but not in the `swagger.yaml`. This results in swagger documentation showing the value as an empty object.

**JSON**

```json
      "properties": {
        "timestamp": {
          "type": "string",
          "description": "...",
          "example": "1995-09-07T10:40:52Z",
          "format": "date-time"
        }
      },
```

**YAML**

```yaml
    properties:
      timestamp:
        description: '...'
        example: 1995-09-07T10:40:52Z
        format: date-time
        type: string
```

**Design**

```go
package design

import (
	. "github.com/goadesign/goa/design"
	. "github.com/goadesign/goa/design/apidsl"
)

var _ = API("adder", func() {
	Title("Demo API")
	Host("demo.default")
	Scheme("http")
})

var Foo = MediaType("application/comment+json", func() {
	Description("...")
	Reference(CreateFooPayload)
	Attributes(func() {
		Attribute("timestamp", DateTime, "...")
	})
	View("default", func() {
		Attribute("timestamp")
	})
})

var CreateFooPayload = Type("CreateFooPayload", func() {
	Description("...")
})

var _ = Resource("foo", func() {
	DefaultMedia(Foo)
	BasePath("/foo")

	Action("create", func() {
		Routing(POST(""))
		Description("...")
		Payload(CreateFooPayload)
		Response(OK, func() {
			Media(Foo, "default")
		})
	})
})
```

Here's a preview with the incorrect value, using the [Swagger Editor](https://editor.swagger.io/)

<img width="918" alt="screen shot 2017-08-28 at 11 19 23 pm" src="https://user-images.githubusercontent.com/727262/29794240-641355c6-8c47-11e7-943e-6ce60808b27c.png">

**Comment by raphael** [comment]
Thank you for the detailed report. Honestly I'm not sure what to do here. The Swagger spec for the example field states that example is:
>A free-form property to include an example of an instance for this schema.
and the type is "Any". The example for example :) in the spec is:

```yaml
example:
  name: Puma
  id: 1
```

You'll note that the example is an object formatted as YAML - not a string. The YAML generated by goagen is valid and represents the value correctly. The YAML is generated using the `gopkg.in/yaml.v2` package so the code in `goa` has no direct control on whether to add quotes or not. One workaround would be to hack the swagger generator to return a quoted string for the DateTime example:

```diff
@@ -445,7 +445,12 @@ func buildAttributeSchema(api *design.APIDefinition, s *JSONSchema, at *design.A
 	}
 	s.DefaultValue = toStringMap(at.DefaultValue)
 	s.Description = at.Description
-	s.Example = at.GenerateExample(api.RandomGenerator(), nil)
+	example := at.GenerateExample(api.RandomGenerator(), nil)
+	if at.Type.Kind() == design.DateTimeKind {
+		s.Example = fmt.Sprintf("%q", example)
+	} else {
+		s.Example = example
+	}
 	val := at.Validation
 	if val == nil {
 		return s
```

but that's quite ugly and doesn't produce exactly what you'd want (i.e. it produces a double quoted string instead of just a quoted string).

It seems to be an issue with the swagger editor and not with goa, please let me know if I've missed something.

**Comment by wayneashleyberry** [comment]
@raphael thank you for looking into this, I agree with you - this must be an issue with the swagger editor.

**Comment by raphael** [comment]
Just a note that DateTime values are quoted in `v2`.

**Comment by dinob68** [comment]
I am finding that swagger is riddled with issues and bad or not helpful documentation.

Similarly, I use @Schema to provide schema definition for my OffsetDateTime and give it example formatted as "19680210" so that request model example for my POST request shows the format I want this date to be displayed as example, but that does not work

```
    @NotNull
    @Schema(description = "Birthdate of customer.", example = "19680228", format = "yyyyMMdd", required = true, nullable = false)
    private OffsetDateTime birthDate;
```

Even though I provided example, neither my model containing this field, nor the example  body generated by swagger in Try it out body shows in this format but rather like 

```
{
  "birthDate": "2022-06-23T21:50:03.503Z",
  ...
}
```
