### ISSUE TITLE
goagen generates pointer to anonymous struct despite attribute is declared required

### ISSUE THREAD

**Issue by seletskiy** [goadesign/goa#1381]
### `design/design.go`

```
package bug

import (
	. "github.com/goadesign/goa/design"
	. "github.com/goadesign/goa/design/apidsl"
)

var (
	Bug = MediaType(
		"application/vnd.example.object+json",
		func() {
			Attributes(func() {
				Attribute("object", func() {
					Attribute("field", Integer)
				})

				Required("object")
			})

			View("default", func() {
				Attribute("object")

				Required("object")
			})
		},
	)
)

func init() {
	API("bug", func() {
		Version("1")
	})

	Resource("default", func() {
		Action("get", func() {
			Routing(GET("/"))

			Response(OK, func() {
				Media(Bug, "default")
			})
		})
	})
}
```

After running `goagen` it produces following code for the declared MediaType:
```
# app/media_types.go

type ExampleObject struct {
	Object *struct {
		Field *int `form:"field,omitempty" json:"field,omitempty" xml:"field,omitempty"`
	} `form:"object" json:"object" xml:"object"`
}
```

Basically, it produces type which is impossible to instantiate without boilerplate code.

Maybe I miss something, but there should be a way to create type without pointer to a struct as field of MediaType.

**Comment by raphael** [comment]
This is by design. Fields of type `struct` are always pointers. I don't understand the comment though:
>Basically, it produces type which is impossible to instantiate without boilerplate code.
The Go syntax for declaring these fields is the same whether it holds a pointer or not...

**Comment by seletskiy** [comment]
@raphael:

> The Go syntax for declaring these fields is the same whether it holds a pointer or not...

How will you instantiate following `reply` variable of `ExampleObject` type with, say, `Object -> Field = 2`?

```go
var reply = ExampleObject{
    Object: ???
}
```

The only way to do it (as far as I know, correct me if I wrong) is to use anonymous struct, which is **extremely** cumbersome:

```go
value := 2
reply := ExampleObject{
	Object: &struct {
		Field *int `form:"field,omitempty" json:"field,omitempty" xml:"field,omitempty"`
	}{
		Field: &value,
	},
}
```

And yes, you need to specify annotations, otherwise it will not compile.

The only workaround here is to use intermediate types everywhere in the API, which does not look like a good design solution to me.

If anonymous structs were not declared as pointers, I could write:

```go
value := 2
reply := ExampleObject{}
reply.Object.Field = &value
```

**Comment by raphael** [comment]
Thanks for the clarification. I have to admit I'm not quite sure what the best way to proceed is, a few thoughts:

1. There is more involved that just initialization convenience wrt using pointers or not. For example it means the field is passed by value instead of reference.

2. It is probably OK to generate a value field for the case described above even considering (1) because it's no likely that such fields would be set or retrieved outside of accessing them via the parent struct. However this is not the case for fields that use an explicitly designed type. For these fields you probably want to use pointers even though they are required (and have the current behavior of validation that the field is not null when unmarshaling). So now we end up with different behaviors wrt using a pointer or not depending on whether the design is using an explicit type or an implicit one...

3. The implementation would be touching part of the code that's already quite tricky (the algorithms to determine whether or not to use pointers to define fields already have to deal with a number of corner cases).

Given all this I would be inclined to say that the best course of action would be to define the intermediary type explicitly. However I'd like to understand the use case a bit better. Are you using this often? can you describe a little bit the use case?

Thanks for the discussion!

**Comment by seletskiy** [comment]
@raphael: Thanks for the answer.

Actually, I do not know now what's better solution will be. So let's just keep that issue at present state until clear path will not reveal itself.
