### ISSUE TITLE
goa v2: http: multiple response.WriteHeader calls

### ISSUE THREAD

**Issue by jsimonetti** [goadesign/goa#1452]
Consider the following design:
```
package design

import (
	. "goa.design/goa/http/design"
	. "goa.design/goa/http/dsl"
)

var _ = API("agent", func() {
	Title("agent")
	Version("0.1")
	Server("http://localhost:8080")
})

var _ = Service("agent", func() {
	HTTP(func() {
		Path("/agent")
	})

	Method("show", func() {
		Payload(func() {
			Attribute("interface", String)
			Required("interface")
		})
		Result(String)
		HTTP(func() {
			GET("/{interface}")
			Response(StatusNoContent)
		})
	})
})
```
When calling the `show` endpoint you will receive an error in the server console:
`2017/11/20 13:27:29 http: multiple response.WriteHeader calls`

This is probably due to an issue with the `Response` saying there is no content (status 204), but the `Result` still allows for a result to be written.

**Comment by nitinmohan87** [comment]
Looking at the generated files for your DSL above
```
# gen/http/agent/server/encode_decode.go
// EncodeShowResponse returns an encoder for responses returned by the agent
// show endpoint.
func EncodeShowResponse(encoder func(context.Context, http.ResponseWriter) goahttp.Encoder) func(context.Context, http.ResponseWriter, interface{}) error {
  return func(ctx context.Context, w http.ResponseWriter, v interface{}) error {
    res := v.(string)
    enc := encoder(ctx, w)
    body := res
    w.WriteHeader(http.StatusNoContent)
    return enc.Encode(body)
  }
}
```
Goa writes a 204 response code to the headers and then `net/http` when encoding the body finds out that 204 HTTP code cannot have a body and returns an error. Goa then tries to write the error code (500 in this case) to the response headers again which results in multiple `response.WriteHeader` calls. By making a HTTP request to the show endpoint, I am seeing that the server logs a 500 error, but the client receives a 204 response.

Anyway, the DSL above is incorrect because the HTTP 204 code cannot have a response body. You can override the `Result` inside the HTTP expression as follows
```
         Method("show", func() {
		Payload(func() {
			Attribute("interface", String)
			Required("interface")
		})
		Result(String)
		HTTP(func() {
			GET("/{interface}")
			Response(StatusNoContent, func(){
                                Body(Empty)   // override Result
                        })
		})
	})
```
PR #1460 should now identify such cases and throw an error during validation.
