### ISSUE TITLE
goagen is also deleting Subversion .svn folders

### ISSUE THREAD

**Issue by dkeza** [goadesign/goa#1454]
Using goagen v1.3.0 on Windows 10 with svn (Subversion) version 1.5.6.

When I am generating new code with goagen, goagen is deleting this folders:

```
app\test
app
client
swagger
tool\cli
tool
```
and creating those folders again, with new files. That is all fine.

But, unfortunately, svn 1.5.6 relies on readonly hidden folder .svn in every child folder, in order to detect code changes, and goagen is also deleting all .svn subfolders. Because of that, my source version control is not working after running goagen.

Maybe we can add new flag to goagen command -i with name of folder which should be ignored?
I looked into code, and have found call to os.RemoveAll command in various places in various go files. Perhaps we should call some wrapper function, where this ignored folder should be checked?

I must say, I am newbie in Go, but I would gladly try to create PR with this change, when we need it.

**Comment by raphael** [comment]
Thank you for the report! I would gladly accept a PR that fixed this. 

I think what needs to be done is look at the `gen_app`, `gen_client`, `gen_schema`, `gen_swagger` and `gen_js` packages and for each replace the call to remove the output directory with one that removes all the files in it except for a white-list which would only contain `.svn` for now (maybe `.git` too to allow for git submodules? - not sure). Note that the `gen_main` and `gen_controller` don't need to be changed because then don't delete folders.
