### ISSUE TITLE
"method_not_allowed","status":405

### ISSUE THREAD

**Issue by evt** [goadesign/goa#1457]
Greetings,

I have an endpoint handling `POST /example` requests, but when I try sending `POST /example/` (with a trailing slash) service returns:
```
{"id":"11VuJL1S","code":"method_not_allowed","status":405,"detail":"Method GET must be POST","meta":{"allowed":"POST","method":"GET"}}
```
I probably miss something but expect service to return either "404 Not found" error or handle by action defined for `POST /example` request.

Looking forward to your reply.

Cheers
Eugene

**Comment by raphael** [comment]
What's happening here is that the router does a automatic redirect of the route ending with `/` to the route with no trailing slash.  Most clients make a `GET` request  when following redirects independently of what the initial HTTP request method is hence the behavior you are observing. There are many ways to address this behavior should it not be acceptable to you: define the route with a trailing slash, make the client follow the redirect with a POST instead of a GET (requires overriding the default Go HTTP client behavior if using Go in the client) or provide your own router that does not have that behavior (override the service `Mux` field with your own implementation).
