### ISSUE TITLE
tool/secure-cli/main.go is not generated with 'goagen client'

### ISSUE THREAD

**Issue by slaterx** [goadesign/goa#1512]
Using macOS 10.12.6.

Adding to your existing design.go/project a security scheme does not generate a secure-cli. Using, for example the security example (https://github.com/goadesign/examples/tree/master/security), running ```goagen client``` generates only a tool/cli/commands.go:

```
➜ goagen client -d security/design        
tool/cli
tool/cli/commands.go
client
client/client.go
client/api_key.go
client/basic.go
client/jwt.go
client/oauth2.go
client/oauth2_provider.go
client/user_types.go
client/media_types.go
``` 

In this scenario, I would need to run ```goagen bootstrap```in order to obtain a tool/secure-cli/main.go. 

After that, any changes in your design.go (even selecting a completely different security scheme) does not regenerate tool/secure-cli/main.go, unless you bootstrap again.

Reproducible on:
```
➜ goagen version
goagen v1.3.1
The goa generation tool.
```

**Comment by raphael** [comment]
This is by design. The tool `main.go` is generated as a starting point - the idea being that you'll most likely need to configure it for your use case. The `bootstrap` and `client` commands do not override scaffold code - only code that is "owned" by the tool such as the `app` directory or the `client` directory except for the tool main. 

FYI this whole story is made clearer in `v2` where the `gen` command generates code that is re-generated each time and cannot be modified while the `example` command generates example main for both the services and clients and does not override existing files.

**Comment by slaterx** [comment]
Thanks @raphael.

Since I was 'adding' security features to my design, that ended up adding more scaffolding, I expected main.go to be updated with brand new added scaffolding, which didn't happen because the file already existed. Would it be the case to have on v2 an area on main.go for that?

**Comment by raphael** [comment]
If you need to use the tool in this way then simply delete the file before calling the `client` command (write a script that does the `rm` and runs `goagen` for example). `v2` does not change that behavior.
