### ISSUE TITLE
support existing structs in the design responses?

### ISSUE THREAD

**Issue by jstrachan** [goadesign/goa#1513]
is there a way to take an existing golang struct and convert it into a Type in a design so it can be used as a resource response while also generating the swagger? I like the design option but there are times when you wish to reuse existing structs to implement a REST API; so having a hybrid approach would be most useful.

I guess in a design the `a.Type(name, func() { ... })` allows for a function which does introspection on an existing golang struct; though it'd be nice if the controller code generation would avoid re-generating the same struct again.

Has anyone ever done such a thing or is goa only for design first, of all structs in the response?

**Comment by raphael** [comment]
One thing to remember here is that the goa design isn't meant to be driving only Go and Swagger code. There's also a JavaScript generator for example and with plugins you can (and some have) generate clients in different languages, generate config files for K8 etc. So long story short it would be difficult if not impossible to mix pure Go structs with design types.

That being said one point that's particularly painful is the fact that if you describe a type that you need to use in your code (e.g. because pre-existing in a package your service consumes) the you need to write code that converts to and from the generated type. For this specific problem the DSL in `v2` introduces the functions [CreateFrom](https://godoc.org/goa.design/goa/dsl#CreateFrom) and [ConvertTo](https://godoc.org/goa.design/goa/dsl#ConvertTo) which allow you to specify Go types that you want to use in your code. The code generator uses reflection to create conversion algorithms from and to the given Go type respectively.

**Comment by jstrachan** [comment]
@raphael awesome thanks! I think those methods should do the trick
