### ISSUE TITLE
Issue with Parent service in route

### ISSUE THREAD

**Issue by kumarsiva07** [goadesign/goa#1516]
![image](https://user-images.githubusercontent.com/7725174/35610978-7a82802c-0689-11e8-9214-69a365f4b26a.png)

I need route like /parent/{parent_id}/child/{id} . I tried all possible ways. That last uncommented one is working. But i think it's not a right ways.  Parent("parent") is expecting like **/parent/**{id}**/child/{id}**

But the problem is we need parent service id should be in some other attribute say parent_id. Then only we can use **id** for child service.

https://gitlab.com/kossaka/goa-example/blob/master/cellar/design/child.go#L10

**Comment by raphael** [comment]
The names of the parameters must be unique when building the absolute path from the parent path. The problem here is that both the parent and child `show` methods use `{id}` in their HTTP path so there is no way to tell which one corresponds to the payload `id` attribute. The design needs to use unique attribute names for attributes used to build a HTTP path. So in your design in the `Parent` service for the `show` method use `parent_id` - or in the `Child` service use `child_id` or anything that makes more sense for your use case as long as both don't end up using `id`.
