### ISSUE TITLE
When Auth middleware returns Error, CORS headers are not set

### ISSUE THREAD

**Issue by faxal** [goadesign/goa#1518]

**Comment by kumarsiva07** [comment]
Check your order of middlewares.  CORS should be inserted before Auth middleware

**Comment by faxal** [comment]
I'm using `app.UseOAuth2Middleware` to specify Auth middleware.

**Comment by raphael** [comment]
Please provide a complete design and code that shows the problem and describe what what is expected vs. what is generated.

**Comment by agnivade** [comment]
This issue is still there. CORS is not a middleware so I have no contol over it. 

But I have a custom middleware which implements basic auth. And on failure to authenticate, the cors headers don't get sent. I have to manually set them. It does not lead to a good user experience because I have to do the work twice.
