### ISSUE TITLE
Plans for a reverse goagen

### ISSUE THREAD

**Issue by leowmjw** [goadesign/goa#160]
Any plans to introduce the ability to create DSL + API from JSON-Schema or Swagger (reverse of goagen)

For example; I want to be able to the a very comprehensive JSON Schemas like below and have the DSL/API being generated: 
(http://www.popoloproject.com/specs/#json-schema)

Thanks for clarifying!

**Comment by raphael** [comment]
This is something I've thought about but no concrete plan at the moment. If anyone feels like tackling that work I'd be more than happy to help.

**Comment by verdverm** [comment]
this could be an alternative to bootstrapping from a  design folder, as on option on the CLI.

Parse the json schema into the AST and then the rest of the pipeline should remain the same.
(Ideally the Goa generated schema should match the input)
(This invocation of the CLI ought to generate the design folder as well, so one could start with a simple schema and add say validation and other such things.)

sound about right?

**Comment by raphael** [comment]
That could be one way yes. The drawback of that approach is that the goa DSL allows you to express more than what Swagger or JSON schema can (e.g. gorma, CORS support etc.). So you would end up with two "sources of truth".

Another approach that seems to make more sense to me but is also more difficult to implement would be to have a JSON Schema or Swagger to goa DSL translator. This would be a one time bootstrap process which would basically help get started with goa and / or port APIs to goa. The use case is slightly different but in the end I believe is also more beneficial.

**Comment by verdverm** [comment]
Agree with the second approach

**Comment by tchssk** [comment]
I'm trying to create this at https://github.com/tchssk/ago. I would appreciate telling me your opinion. @raphael

**Comment by raphael** [comment]
This looks great! and I love the name :) The direction at a high level looks right to me (i.e. unmarshaling into `genswagger.Swagger` then traversing the data structure to generate the DSL). Here are a few random thoughts:

1. It may be helpful to specify what each template expect as input in a comment (e.g. an `APIDefinition` or a `ResourceDefinition` etc.)

2. As you probably already know it's going to be "interesting" to reverse-engineer the views for media types. You'll probably need to parse the identifier and extract the information from it. This will also be necessary to identify `CollectionOf` media types.

3. When you get to types it would be good if there was an option to generate them in a different file (package even so that the types can be generated in e.g. a `public` sub-package of `design`).

4. It may be helpful to change the swagger generator so that it adds swagger extensions that contain metadata that makes the reverse engineering a lot easier or even possible in the first place. This would be needed to properly re-create Response templates for example.

Thank you for doing this!

**Comment by tchssk** [comment]
Thank you for your replying.

ago is an angram of goa, and it means going back to before using goa :)

1. That will be helpful. I'll add the comments for each template.
2. Yes, it will be difficult work...
3. I was thinking the same thing. We probably should make it possible to specify all DSLs that can be top level in `design`. (i.e. `API`, `Type`, `MediaType` and `Resource`)
4. I think so too. goa can have more information than swagger. We have to use swagger extensions to complement them.

**Comment by Raffo** [comment]
Already a feature parity with swagger would be great, I would postpone writing the extensions to a later task.

**Comment by raphael** [comment]
The point though was that it may be necessary to add some just to be able to properly reverse engineer the DSL. Agreed that we can leave improvements for later.

**Comment by raphael** [comment]
closing this old issue, there's a repo now: https://github.com/tchssk/ago
