### ISSUE TITLE
v2 Error decoding error

### ISSUE THREAD

**Issue by psschroeter** [goadesign/goa#1669]
Currently in v2 theres a few classes of error that can get returned by a server
1. clientErrors generated by goa for Validation, parsing, etc - Most of these are 400 Bad request errors
2. other errors sometimes returned by server code (i.e. returning a fmt.Errorf or error from a function call. These mostly become 400 internal it seems like unless they're temporary errors
3. goa.ServiceError - Can be anything, including 400 bad request.

When the client tries to decode these errors, it gets 1 + 3 if you have a 400 bad_request defined for type 3 in your goa design. It matches on the http.Response.StatusCode in the encode_decode.go and tries to decode it as that type when it's something else. The decoding fails due to validation errors so the error gets returned as a validation error, obscuring the original error.

**Comment by psschroeter** [comment]
Example gist:
https://gist.github.com/psschroeter/79ac968066cd46025a15a577dc08f6b6

For gen/http/dummy/client/encode_decode.go
If in the server code you return a `fmt.Errorf("Error occurred!")` the server encodes it as an internal error (not a goa.ServiceError). Client messes up decoding it and returns the fmt.Errorf("invalid response: %s") instead of the real error

**Comment by psschroeter** [comment]
Woops messed up original description. Said 500 internal when I meant 400 bad request -- updated gist

**Comment by raphael** [comment]
So methods should not return just straight errors, they should use the generated `MakeXXX` functions to return an error that correspond to one of the errors described in the design. But even in this case I guess there's a potential conflict between the built-in validation errors and custom errors with status code 400. We could change the generated code so that it handles the built-in validation error types explicitly and then falls back to trying the custom errors when these fail. Would that solve your issue?

**Comment by psschroeter** [comment]
Bump. Yes that sounds good - am changing everything to use MakeXXX when possible. Would also be nice to map to InternalServerError by default for all errors that aren't validation type errors.

**Comment by raphael** [comment]
Thanks, this is fixed in the latest v2.
