### ISSUE TITLE
Need design attribute datatype for time.Time

### ISSUE THREAD

**Issue by kumarsiva07** [goadesign/goa#1671]
Need design attribute datatype for time.Time.

**Comment by raphael** [comment]
The intent with v2 is to leave the `Time` type out as supporting more data types natively is a lot of work. In particular supporting time is tricky because for example there's no native support in OpenAPI or the way JavaScript encodes them is not standard. So in v2 the idea is to use a `String` and a format to specify that the string carries a date time value.
