### ISSUE TITLE
Create v3 to support Go modules

### ISSUE THREAD

**Issue by raphael** [goadesign/goa#1959]
Goal
-----
We want to keep supporting goa v1 but also want to make goa v2 a clearly separate framework as the differences between the two are fairly fundamental. Today one can use v1 by using the package path `github.com/goadesign/goa` and v2 with `goa.design/goa` and we'd like to keep that going forward if only for backwards compatibility. The actual source code for v2 is in the `v2` branch in the `github.com/goadesign/goa` repo. The `https://goa.design/goa` endpoint redirects `go get` to `gopkg.in/goa/v2` which points to the `v2` branch.

Problem
---------
The introduction of Go modules breaks the scheme described above as the `go` tool now does a local checkout of the branch which is incompatible with the use of `gopkg.in`.

Proposed solution
---------------------
The proposal consists of moving the `v2` branch to its own repo, e.g. `github.com/goadesign/goa2`.

Other considered solutions
------------------------------
An alternative would be to create a `v2` directory in the existing repo but that does not seem attractive because:
- It would be confusing for newcomers (v1 still leaves under the top level directory).
- It would obfuscate where most of the work will actually happen in the future.
- It would be a breaking changes for v2 as all the import paths would have to be modified to append `v2`

Notes
-------
This proposal does not address Go modules support in `v1`.

**Comment by raphael** [comment]
I have put more thoughts into this and I'm now wondering whether a better approach wouldn't be to simply merge the `v2` branch in to the `master` branch of this repo (`github.com/goadesign/goa`) and keep `v2` up-to-date with `master`. We would create v2 releases by creating tags which would make it possible to use Go modules by specifying the appropriate version in the module definition file i.e.:
```go
module github.com/you/hello

require goadesign/goa v2.0.0
```

**Comment by CuBiC3D** [comment]
I think merging v2 into master and tagging would be the best way to support modules, but the import would still be `require goadesign/goa/v2 v2.0.0` according to https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher and needs to be set in go.mod with the v2.0.0 tag. Golang did a very confusing step towards modules =/

Waiting for the support to finally migrate to v2 and modules on my projects :)

**Comment by nitinmohan87** [comment]
@raphael We are at a point where we are not adding new features to goa v2. We have been fixing bugs and writing docs to release v2. But without having v2 branch merged to master, we really can't test `go modules` support. We should probably start doing that.

**Comment by k3a** [comment]
A separate repo or merge to master would be definitely better than a subdirectory.

I am not sure if merge to master would be the best, though. Goa2 is quite a major overhaul, maybe a separate repo would be  clearer option as it would avoid setting tags to go.mod manually and it would let other tools like IDEs pick the correct dependency right away without any tag hacking...

**Comment by raphael** [comment]
@k3a can you expend a bit on what you mean by "tag hacking"?

**Comment by k3a** [comment]
Sometimes I create a new project and initiate go modules for it. Then I write a new import in Visual Studio code, save the file and it uses go tools to automatically fetch that new dependency and add it to go.mod. I don't know if it uses the last commit or last release tag. But it would be cool if it took Goa v2 by default, otherwise it would require manual go.mod edit and maybe VSCode would be confused, requiring it to close and reopen. Not a big deal, but it wouldn't be "automatic".

Separately, do you think it would be somehow possible to get "goagen" binary for the version used in a project in order to get reproducible builds? So far I've used "go get ..." on the global scope but I think it can get out of sync with the version used in the project eventually.

**Comment by raphael** [comment]
OK yeah I see your point. It seems though that creating a go.mod file for your project is going to become standard practice as Go standardizes on it. I would also expect that having to specify the version of your dependencies is going to be something that users get accustom to and that tools will help with going forward. In particular the import path will contain the version so I expect most tools to be able to pick that up automatically.

Today the way we make sure that the tool used to generate the code is always the same is by compiling the version under the `vendor` directory and using that to generate. We encapsulate all this within a Makefile.

**Comment by k3a** [comment]
I've looked the problem again. Previously I wasn't aware about the most recent changes in Go module support and the original issue description didn't mention the current state and it all seemed too confusing.

I found this Go blog page the most helpful: https://blog.golang.org/using-go-modules
It includes clear examples of the workflow and it's easy to follow and my Go 1.12.4 fully supports it.

Surprisingly, they really prefer `/v**` sub-directory in a repo. I still find it weird because if you would specify goadesign/goa/v2, the cloned data would probably contain complete repo with v1 and v2 (and other v* subdirectories) kind of unnecessarily, is that correct? 

It seems to me that `v*` subdirectory semantic is just good to avoid naming confusion `import "goadesign/goa/v2"` makes it clear that it is just a "2" version of "goa". But I don't see anything bad about a separate repo `import "goadesign/goa2"`.

Maybe I am missing something - please tell me so - but I see another confusing thing about subdirectories and that is Github Issues. In every issue there now need to be a tag or prefix to mention version number "generation" it refer to. Separate repos would be free from this confusion.

**Comment by CuBiC3D** [comment]
@k3a 
> Surprisingly, they really prefer /v** sub-directory in a repo. I still find it weird because if you would specify goadesign/goa/v2, the cloned data would probably contain complete repo with v1 and v2 (and other v* subdirectories) kind of unnecessarily, is that correct?

Actually no, not correct. Go does not have a preference, but gives you a variety of possibilities. Module paths ending in /v* do not imply that the repository has a directory containing an actual version - this is just a module notation which can refer to a semantically tagged version. See above, where I linked a releasing guide for v2+. You really do not want to have a project like goa live in versioned directories inside a repository ;)

**Comment by k3a** [comment]
No, according to the example in the blog post it seems it indeed implies sub-directory. Please have a look here https://github.com/rsc/quote (btw I've edited my previous comment here).

**Comment by CuBiC3D** [comment]
Sorry it's hard to write while you edit your comments every minute.
I see that it's using directories in the example, I just said that it does not imply that generally (and does not prefer, not does it).

**Comment by raphael** [comment]
Thanks for the discussion guys! As @CuBiC3D mentioned module versioning does not require subdirectories but merely that the module path has the version appended to it. I put together a POC for v3 (don't want to break v2). v3 is functionally exactly the same as v2 - the only difference is that it supports Go modules. Take a look at https://github.com/goadesign/goa/blob/v3/doc.go for an example of how to use it. We should test v3 with designs that are in GOPATH as well and if all works well I'm planning on making the v3 branch the default on GitHub which alleviates the issue of newcomers seeing the latest and greatest but also keeps the master branch intact for people that are currently using it.

**Comment by CuBiC3D** [comment]
@raphael the well known 'we make a v3' method since modules introduction, the echo framework guys from labstack did the same with v4 ;) I'll test as soon as I can and port an API project to goa 2.

**Comment by CuBiC3D** [comment]
Ok, in terms of using v3 as modules everything seems to be fine - no problems there.

The porting part however is a bit of pain at the moment regarding auth. We kinda 'misuse' BasicAuth in v1 by supplying scopes to it at the moment. This allows us to extract the scopes via `goa.ContextRequiredScopes(ctx)` in the middleware, authenticate the user against LDAP and match the scopes against LDAP groups. It even generates correct swagger, which contains the required scope, e.g.: `BasicAuth (users:list)`. As far as I can see, v3 does not allow scopes to be defined on `Security(BasicAuth)` and also requires to have username and password payload defined on every method, instead of handling everything in middleware only.

That's a bit off-topic, is there a better place to discuss such things?

**Comment by raphael** [comment]
Thanks for the feedback @CuBiC3D - I suggest you open a separate issue to discuss your need.

**Comment by raphael** [comment]
v2 and v3 have been released, closing this issue - thank you for all the input!
