### ISSUE TITLE
V3: Any type is not supported in gRPC

### ISSUE THREAD

**Issue by lneoe** [goadesign/goa#2188]
the goa version is:

it same with #2034 , the only different is I use v3

```shell
$ goa version
goa version v3.0.2
```

```golang
package design

import . "goa.design/goa/v3/dsl"

var _ = Service("Something", func() {
	Method("create", func() {
		Payload(func() {
			Field(1, "name", String)
			Field(2, "bad", Any)
		})
		Result(Empty)

		GRPC(func() {
			Response(CodeOK)
		})
	})
})
```

run `gen` I got 
```shell
$ goa gen calcsvc/design -o impl

exit status 1
service "Something" gRPC endpoint "create": Attribute "bad" is Any type which is not supported in gRPC
```

after searching I found a fix from #2037, but it only in v2

**Comment by raphael** [comment]
Yes, the type `Any` is not supported with the gRPC encoding. gRPC relies on the type being known at compile time to generate the proper serialization code. The fix above simply makes sure that a proper error message is shown when `Any` is used in designs using gRPC rather than having the tool panic.
