### ISSUE TITLE
Add support in v2/v3 for "application/octet-stream" to/from []byte (Bytes) bodies.

### ISSUE THREAD

**Issue by cquinn** [goadesign/goa#2197]
Carl:
Using Goa v3, I am trying to create a method that accepts a Put with an int value in the path (easy) but then just raw bytes in the Body. Essentially a “application/octet-stream”. But that doesn’t appear to be built-in, and I haven’t figured out how to define a Decoder/Encoder for just plain bytes. 

Raphael:
It would make sense to add "application/octet-stream" to the list of content types that the default Goa encoder and decoder understand.

A no-op decoder could look like:
```type Decoder io.ReadCloser
func (dec Decoder) Decode(v interface{}) error {
    buf, ok := v.(*[]byte)
    if !ok {
        return fmt.Errorf("unexpected decoding target %T, must be *[]byte", v)
    }
   b, err := ioutil.ReadAll(dec)
   if err != nil {
       return err
   }
   dec.Close()
   *buf = b
}```
And a no-op encoder:
```type Encoder io.Writer
func (enc Encoder) Encode(v interface{}) error {
    buf, ok := v.([]byte)
    if !ok {
        return fmt.Errorf("unexpected encoding target %T, must be []byte", v)
    }
   _, err := enc.Write(buf)
   return err
}```

We could then add the corresponding switch on "application/octet-stream" to `RequestDecoder` and `ResponseEncoder` in http/encoding.go (Writing the corresponding NewXXX functions is left as an exercise to the reader :wink: )

**Comment by tomjohnburton** [comment]
Any updates? I was hoping for a similar support upgrade for application/x-www-form-urlencoded

https://github.com/goadesign/goa/issues/2208

**Comment by Va1** [comment]
flexibility in request/response mime-types is highly anticipated. we've migrated to v3 and realized this too late

**Comment by raphael** [comment]
Agree that it is important for Goa to make it possible to support any mime type. This issue is about adding the ability for the Goa *default* encoder to support raw byte encoding. Goa makes it possible to plug in any encoder/decoder, there is no way that it could support all the possible mime types and the approach taken here is to make it composable.

Another way to state the above is to say that the code generated in the `gen` package which cannot be modified does not directly instantiate the decoder and encoder. The instantiation is done in the main package and the corresponding encoder and decoder factory functions are provided to the generated code. The default example generator makes use of the default functions ([RequestDecoder](https://github.com/goadesign/goa/blob/v3/http/encoding.go#L61), [ResponseEncoder](https://github.com/goadesign/goa/blob/v3/http/encoding.go#L96), [RequestEncoder](https://github.com/goadesign/goa/blob/v3/http/encoding.go#L168) and [ResponseDecoder](https://github.com/goadesign/goa/blob/v3/http/encoding.go#L168)) however your code is absolutely free to override these and provide your own ([here](https://github.com/goadesign/examples/blob/master/basic/cmd/calc/http.go#L36-L37) for example).

**Comment by tomjohnburton** [comment]
Thank you for your response @raphael 

I think it would be wise to update the documentation on adding custom encoders as this is no longer valid.
```
var _ = API("My API", func() {
    // ...
    Consumes("application/msgpack", func() {
        Package("github.com/goadesign/goa/encoding/msgpack")
    })
    // ...
})
```

**Comment by raphael** [comment]
Hmm yes good point, thank you.
