### ISSUE TITLE
Cannot use "v" as a payload attribute name

### ISSUE THREAD

**Issue by colvinwellborn** [goadesign/goa#2204]
When a `Method` has an attribute named "v":

```
var _ = Service("foo", func() {
        Method("setKey", func() {
                Payload(func() {
                        Attribute("k", String, "key")
                        Attribute("v", String, "value")
                        Required("k", "v")
                })
                Result(String)
                HTTP(func() {
                        POST("/foo/{k}/{v}")
                        Response(StatusOK)
                })
        })
})
```

... this causes this code to be generated in `gen/http/foo/client/encode_decode.go`:

```
func (c *Client) BuildSetKeyRequest(ctx context.Context, v interface{}) (*http.Request, error) {
        var (
                k string
                v string
        )
        {
                p, ok := v.(*foo.SetKeyPayload)
```

This results in a `v redeclared in this block` compiler error.

**Comment by nitinmohan87** [comment]
I think we should rethink the way we use name scoping. Otherwise, we will keep hitting such bugs all the time. Right now, attribute names can collide with in-built variables, and go packages/keywords we use in the code generation.

Instead of hard-coding variable names in the generated code, we could derive the variable name from the scope based on the attributes in the design and the go packages/keywords used in the package. Also we can have a function-level name scopes (instead of single top-level scope). But this might be a big change.

**Comment by raphael** [comment]
Can you elaborate a bit more on what such a solution would look like? I understand the reasoning here but it seems that there is also a lot of benefit to keeping things simple and simply escaping for the variables used in templates. There are actually not that many cases where clashes can occur, most times the scoping makes it impossible. The current solution is not perfect but feels like the right trade-off. But I could be missing what you are suggesting we do.

**Comment by nitinmohan87** [comment]
I was thinking of something [like this](https://github.com/goadesign/goa/blob/v3/http/codegen/service_data.go#L772-L773)
The above code initializes a NameScope just for the `BuildXXXRequest` function. Looking at the [`BuildXXXRequest` implementation](https://github.com/goadesign/examples/blob/master/basic/gen/http/calc/client/encode_decode.go#L24), we need to add following variables to the scope `v`, `ctx`, `req`, and `err` so that users can use them in their design without causing conflicts.

Likewise, we would initialize separate NameScopes for the Encode and Decode functions.

**Comment by raphael** [comment]
Ah OK yes that makes sense, completely in line with what I was thinking as well.
