### ISSUE TITLE
Extended attributes in ResultType not returned

### ISSUE THREAD

**Issue by jamiebloom** [goadesign/goa#2227]
I've noticed a potential issue with using `Extend` inside a `ResultType` in V2.

**Actual result**
Given a `ResultType` which extends another `Type`, the attributes defined in `ResultType` explicitly are returned, while the attributes in `Type` are silently dropped. I suspect this is happening somewhere in the generated code.

**Expected result**
As above, but with the attribute(s) defined in the `Type` returned.

**Workaround**
Replacing `ResultType` with `Type` in the included design will get around the issue. However, I understand from the DSL docs that `ResultType` should support `Extend`.

I've included a minimal design to reproduce this below - for convenience I've ran `goa gen` and `goa example` and added the generated service to [this repo](https://github.com/jamie-doyle/goa-test).

You should be able to reproduce this by running the above service, making a request using the Goa CLI, and observing that the extended value isn't returned. The service includes hardcoded return values for the sake of simplicity.

```
var Table = Type("Table", func() {
	Description("Describes a table")
	Field(1, "table_id", String, "A table ID", func() {
		Example("some-table-id") // This is never returned
	})
	Required("table_id")
})

var TablePayload = ResultType("TablePayload", func() {
	Extend(Table)
	Field(2, "description", String, "Describes the table being returned") // This is returned
})


var _ = API("Table Info Service", func() {
	Title("Table Info Service")
	Description("Goa test service")

	Server("Table Info Service", func() {
		Services("TableInfo")
		Host("0.0.0.0", func() {
			URI("grpc://0.0.0.0:8000")
		})
	})
})

var _ = Service("TableInfo", func() {
	Method("get_info", func() {
		Payload(func() {
			Field(1, "tableName", String, "Table name", func() {
				Example("myGreatTable")
			})
			Required("tableName")
		})
		Result(TablePayload)
		GRPC(func() {
			Response(CodeOK)
		})
	})
})
```

If this is an issue (and not just me doing design files wrong) I'm happy to open a PR with a fix if someone can point me in the right direction, or to provide more information if it helps diagnose or fix the issue

**Comment by raphael** [comment]
Hello @jamie-doyle, thank you for the report and the detailed repro!
First off a couple of comments on the design above:
1. The syntax for defining result types differs from the syntax for defining types. Result types can define views (that's basically why they exist) and  therefore the attributes definition must be wrapped in a `Attributes` function. See the [docs](https://godoc.org/goa.design/goa/dsl#ResultType) for details.
2. As a convention `Payload` is meant to refer to request payloads, Goa refers to the content of responses as `Result` just to disambiguate (technically the word `Payload` could definitely apply to both).

That being said the issue here is that the `default` view that Goa generates when none is defined explicitly does not indeed include the attributes of the extended type which does seem counter intuitive. The following design defines the default view explicitly and results in the behavior you'd expect:
```go
var TableResult = ResultType("TableResult", func() {
	Extend(Table)
	Attributes(func() {
		Field(2, "description", String, "Describes the table being returned") // This is returned
	})
	View("default", func() {
		Attribute("table_id")
		Attribute("description")
	})
})
```
Thank you for offering to open a PR! The default view is generated in the result type expression finalizer which gets run after the DSL has produced all the expressions which are going to be used to generate the code. The function that generates the default view is here: https://github.com/goadesign/goa/blob/v3/expr/result_type.go#L182-L196. The fix would be to change this function to also include the attributes defined in the extended type recursively if any. Now the Go struct that defines a result type `ResultTypeExpr` contains an anonymous field that holds a `UserTypeExpr` since a result type is really just a type that adds views. The user type expressions struct in turn contains an anonymous field that holds a `AttributeExpr` since a user type is basically an attribute that defines a name so it can be reused. The finalizer of the attribute expression does the copy of the base attributes (attributes that come from extended types), see https://github.com/goadesign/goa/blob/v3/expr/attribute.go#L237-L259. So it seems there may be an ordering problem where the default view gets generated before the attribute expression is properly "expanded". Happy to provide more guidance if needed, thank you for looking into it!
