### ISSUE TITLE
Numeric values in the attribute name of the payload 

### ISSUE THREAD

**Issue by Vshekarappa** [goadesign/goa#2365]
When we use numeric values as part of the field name (attribute name in the payload), it is internally getting converted into a different name and hence it is not taking the value what we pass as an input instead it is considering it as zero(default value as the data type is UInt).

**Example:** By considering the two test attributes `F5ID` and `type` in the payload,
The **_F5ID_** is getting converted as _**F5_ID**_ internally in `gen` code. Seems like when we use numeric values we face this issue.
Ideally we need to pass _F5ID_ as per payload, but that's not accepted while _F5_ID_ is

For the below payload, F5ID is considered as zero
`{
          "F5ID": 599777862,
          "type": "test"
       }`

but when we change the attribute name as F5_ID then it is taking the value whatever we are passing(as expected)
`{
        "F5_ID": 599777862,
         "type": "test"
}`

For our service, as per the standard naming convention we have changed it to snake case.
But it seems like there is a bug in Goa which can be addressed.

**Comment by raphael** [comment]
What's happening here is that the proto file generator is formatting the message fields using snake_case because that's the convention being used for .proto files. See https://developers.google.com/protocol-buffers/docs/style#message-and-field-names - so I believe this works as expected and you need to adjust how you build the command line arguments.
