### ISSUE TITLE
cannot find package when the project has vendor directory in v3

### ISSUE THREAD

**Issue by heisonyee** [goadesign/goa#2544]
Env:
os: macOS 10.15.4
go version: 1.14.2
go module: enabled

As the title mentioned, when  the vendor directory  has been generated in the project,  runs cmd
**goa gen github.com/xxx/demo/design -o internal**
will cause error as below:
**main.go:19:2: cannot find package "." in:
        /XXXXX/vendor/goa.design/goa/v3/codegen/generator**

After vendor directory deleted, **goa gen** cmd works fine.

**Comment by saniales** [comment]
Does this happen everytime you have a vendor folder already in place?

re elaborating: do you need to delete vendor directory everytime to run `goa gen` more times?

**Comment by nmaslarski** [comment]
Hello @saniales we have the same issue. It reproduces every time we have a Vendor folder. In order to run the goa gen, I need to delete the vendor.
The error is with bunch of packages 
main.go:18:2: cannot find package "." in:
     .../vendor/goa.design/goa/v3/codegen
main.go:19:2: cannot find package "." in:
      .../vendor/goa.design/goa/v3/codegen/generator

We are using the goa cli installed this way 
GO111MODULE=on go get goa.design/goa/v3/cmd/goa

**Comment by saniales** [comment]
I suggest using goa v2 if you are not using modules, but vendoring. Try that and tell me how it goes ;)

V2 and v3 are identical, except that v3 is built for go modules and not for vendor tools like dep give for etc...
