### ISSUE TITLE
Is it possible to create caste endpoints?

### ISSUE THREAD

**Issue by flymedllva** [goadesign/goa#2796]
I have a code that expects `res http.ResponseWriter, req *http.Request processes` the request itself. Is it possible to make such a handler?

**Comment by raphael** [comment]
There are multiple ways to do this depending on the context:
1. Simply provide your own HTTP handler when creating the HTTP server instead of using the one generated by Goa. This makes sense if you don't intend on using any of the generated marshaling and validation code.
2. Inject the request and response elements you need in the context using a HTTP middleware such as [PopulateRequestContext](https://github.com/goadesign/goa/blob/v3/http/middleware/request.go). This makes sense if you only need specific headers or other transport level information.
3. Inject the HTTP request and response themselves in the context via a HTTP middleware. This makes sense if you want Goa to handle the marshaling / validation but still want access to the underlying transport layers in the business logic. Note that this is not a good practice in general though as it defeats the clean separation of layers.

You may also want to consider using a HTTP middleware to keep transport specific logic in the transport layer.
