### ISSUE TITLE
Allow to make "hidden" fields in the design.go

### ISSUE THREAD

**Issue by lizapolyudova** [goadesign/goa#2924]
It would be nice to support an equivalent of [this annotation](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations#hidden)

I love using goa for auto-generating types and docs from them, but it would be nice not to expose unnecessary internals in public docs.
Is there a `Meta()` annotation which would cause a given field to not be included in the documentation?
At first I considered using `Meta("swagger:generate", "false")`, but it turns out that's only applicable to Methods and Services.

**Comment by raphael** [comment]
Just to make sure I understand: this would make it possible to prevent specific type fields ("attributes") to be rendered in the OpenAPI specification? So something like:

```go
var TypeWithHiddenFields = Type("TypeWithHiddenFields", func() {
    Attribute("hidden", func() {
        Meta("swagger:generate", "false")
    })
})
```

Adding the ability to do the above would be fine, probably not applicable in general (since the generated code does make use of all fields) but could be useful for the case you describe above (i.e. using the generated types in a different context). Would be happy to merge a PR that added that support! For OpenAPI v3 I believe that all that would be needed is update https://github.com/goadesign/goa/blob/bf825b1c2a7bad7aa891c612767e2002f887c923/http/codegen/openapi/v3/types.go#L136 to look for this metadata and skip generation when present (that's just on top of my head though).

**Comment by lizapolyudova** [comment]
Yes, the example you provide would be exactly the API I am looking for. (it's actually the first thing I tried and then read the comments in the Meta function only to realize it doesn't apply to structs)

Thank you for the quick turnaround!
