### ISSUE TITLE
v1-v3 migration codegen ? 

### ISSUE THREAD

**Issue by ashtonian** [goadesign/goa#2945]
I'm migrating an old project to use go modules and part of that upgrade is migrating goa from v1 to v3. I've been able to follow the migration guide and converted the dsl. We had some tooling around programmatically generating though that I'm not quite as clear on and wondering if you could point me in the right direction. 

Here is the snipet from v1.
```golang

func main() {
	genPath := "./apps/api/generated"
	codegen.ParseDSL()
	generateControllers := false
	if !generateControllers {
		codegen.Run(
			genapp.NewGenerator(
				genapp.API(design.Design),
				genapp.Target("gen"),
				genapp.OutDir(genPath),
				genapp.NoTest(true),
			),
			genswagger.NewGenerator(
				genswagger.API(design.Design),
				genswagger.OutDir(genPath),
			),
		)
	} 
```

**Comment by ashtonian** [comment]
Also having problems in general with the code gen cli - the project is part of a module, the desing code is in apps/api/design. When I try to run the cli I get errors:
```sh
 goa gen api apps/api/design/ 
package api is not in GOROOT (/usr/local/Cellar/go/1.17.2/libexec/src/api) 
 goa gen ./apps/api/design/
main.go:17:2: local import "./apps/api/design/" in non-local package

**Comment by raphael** [comment]
Hello a few pointers:
* The code for the tool that Goa generates which ends up generating the final code is here: https://github.com/goadesign/goa/blob/v3/cmd/goa/gen.go#L260-L313 - Basically the function that ends up generating the final code is [Generate](https://github.com/goadesign/goa/blob/v3/codegen/generator/generate.go#L15) from the `codegen` package. 
* `v3` always generates the Swagger files so there's no need to call another function for that. 
* The error above is probably because the path given to `goa gen` is not a valid package import path (the argument should be the Go package path to the design - not the file path). So if your module name is foo and the design package lives under `apps/api/design` then the command line to invoke Goa should be `goa gen foo/apps/api/design`.

Hope this helps!

**Comment by ashtonian** [comment]
exactly what I needed, thanks!
