### ISSUE TITLE
proto: file "error.proto" is already registered

### ISSUE THREAD

**Issue by BVoychev** [goadesign/goa#2949]
The proto world requires you to use distinct names, package-qualified. The message names can be the same, but you should use different package names to keep them isolated. Currently `"goa.design/goa/v3/grpc/pb"` use error package and if another dependency use the same package the following error occurs - `proto: file "error.proto" is already registered`

**Comment by raphael** [comment]
Makes sense, what do you suggest be done? rename the error package to something more specific?

**Comment by ntaylor-barnett** [comment]
I have also just hit this one. Do we have a suggestion for a workaround?

> panic: proto: file "error.proto" is already registered
> 	previously from: "goa.design/goa/v3/grpc/pb"
> 	currently from:  "github.com/googleapis/gax-go/v2/apierror/internal/proto"
> See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

**Comment by raphael** [comment]
I'm open to suggestions here (or better yet a PR! :) ), seems like we may want to make the Goa namespace more specific.

**Comment by BVoychev** [comment]
Thanks @raphael! :)

**Comment by nitinmohan87** [comment]
I haven't investigated this much. Is it something as simple as renaming `error.proto` to something goa-specific, say `goa-error.proto`?

**Comment by nitinmohan87** [comment]
Not sure if I am looking at the right place. According to the [package conflict prevention doc](https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict) we do set the package and go_package in the [goa error proto file](https://github.com/goadesign/goa/blob/v3/grpc/pb/error.proto#L8-L10).

I am not quite sure why the `error.proto` filename is the issue here. The filename is the only thing that is same with the conflicting proto file - https://github.com/googleapis/gax-go/blob/main/v2/apierror/internal/proto/error.proto

**Comment by nitinmohan87** [comment]
Seems like a bug in protobuf that was fixed recently? - https://github.com/golang/protobuf/issues/1122

**Comment by nitinmohan87** [comment]
Investigating more into this.. It seems like to be on the safer side we should place .proto files in a directory that is unique to the owner of the proto (See [this comment](https://github.com/golang/protobuf/issues/1122)) to avoid any namespace conflicts.

That means we could place goa grpc error.proto in $GOA_DIR/grpc/goa/error.proto instead of $GOA_DIR/grpc/pb/error.proto and then generate the pb.go files with the following command
```
protoc --go_out=. --go_opt=paths=source_relative  goa/error.proto
```
This should set the source in error.pb.go to
```
source: goa/error.proto
```
This is how google protobuf repo also organize their .proto files - https://github.com/protocolbuffers/protobuf/tree/master/src/google/protobuf

Hopefully this should do. I can try more tomorrow and come up with a fix.

This also means we should change the protoc command that goa runs to generate the service pb.go like this -https://github.com/goadesign/examples/blob/master/basic/gen/grpc/calc/pb/calc.pb.go#L13

@raphael does this make sense?

**Comment by ntaylor-barnett** [comment]
I have a temporary workaround that will at least unblock you until the fix is made available in GOA.

Add this (or the equivalent) to your go.mod

`replace (
	google.golang.org/protobuf v1.27.1 => google.golang.org/protobuf v1.26.1-0.20210525005349-febffdd88e85
)`

Should get you running again.

**Comment by raphael** [comment]
@nitinmohan87 thanks for looking into this, what you are suggesting makes sense (i.e. making the path `goa/error.proto` instead of `error.proto`). It doesn't seem like this would introduce a breaking change given that the actual Go package import path would remain the same.
