### ISSUE TITLE
Error: "Param" method Can't analysis "type" 

### ISSUE THREAD

**Issue by KerwinKoo** [goadesign/goa#296]
In a resource I defined an `Action` method:

```go
Action("GetTest", func() {
		Routing(GET("/gettest"))
		Description("test")
		Params(func() {
			Param("type")  //error occurred here
		})

		Response(OK, "plain/text")
	})
```

As you can see I set `Param("type")` without being declared at `Routing` (`Routing(GET("/gettest"))`). 

DO `goagen bootstrap -d paperkite/design`:
```
accounts_get.go:15:53: expected 'IDENT', found 'type'
...
values.Set("type", type_)

```

AND,  It removed all go files (like `rm *.go`) in my main project directory.

Modified `Routing(GET("/gettest"))` into `Routing(GET("/gettest/type"))` can resolved this error, but I think it's a big BUG.

**Comment by raphael** [comment]
I think it is a bug but not the one you think :) You can use params that are not path parameters, these correspond to querystring values (you probably know that - just making sure). The problem here I'm guessing is the name of the parameter `type` which happens to be a Go keyword. It looks like `goagen` is doing a poor job at escaping it properly. Try renaming in `kind` for example and my guess is that it will work. I'll look into where `goagen` fails to escape `type`. Thanks for the report!

**Comment by raphael** [comment]
Thanks, this is now fixed.
