### ISSUE TITLE
Is that possible to define Token in one place?

### ISSUE THREAD

**Issue by yogihardi** [goadesign/goa#2998]
Hi,

I want to ask about the way to define `Token()` attribute at once when using JWT Security.

as written on the documentation, when I want to use JWT Security, I need to put `Token` explicitly on every single Method's Payload. ie:

```
          Method("get", func() {
		Payload(func() {
			Token("token")
			Attribute("group", String, "group")
                })
               ...
          })
```

my problem is, I have so many endpoints, and defining the `Token` in every single endpoints is repetitive work. Is there any way to do it at once or let the goa handle it in the background when found `JWT Security` dsl like how it has done in goa v1?

the second problem is, we can't use direct `Type` in Payload when it has `JWTSecurity`.

**design:**

```

// JWTAuth defines a security scheme using JWT.
var JWTAuth = JWTSecurity("jwt", func() {
	Scope("ftp:access", "read access")
	Scope("ftp:admin", "admin access")
})


var _ = Service("hello", func() {
	Security(JWTAuth, func() {
		Scope("ftp:access")
	})
	Method("get", func() {
		Payload(MapOf(String, HelloType))
		HTTP(func() {
			Header("token", String)
			GET("/hello")
			Body(func() {
				Attribute("position")
			})
		})
	})
})

var HelloType = Type("hello.type", func() {
	Attribute("message", String, "message")
	Required("message")
})
```

**result:**
```
exit status 1
service "hello" method "get": payload of method "get" of service "hello" does not define a JWT attribute, use Token to define one
service "hello" HTTP endpoint "get": header "token" not found in payload.
api.go:22: running "goa": exit status 1
```

**Comment by raphael** [comment]
There are two ways that can help with having to define a token on every payload:
1. Define all common attributes in a type and use `Extend` in the payload definition or type. If only the token is common that does not help much because it's replacing one line with another but if there multiple common attributes then this can help.
2. Define your own `PayloadWithToken` function that has the same signature as `Payload` and takes care of defining the token attribute.

The problem with the design with the token in the header is that the payload does not specify a token attribute. The method payload should define all the attributes that are transmitted through the request including attributes transmitted via the request body, headers, path parameters and query string. The `HTTP` function then defines where the attribute comes from. See https://goa.design/design/http_mapping/ for details.

**Comment by yogihardi** [comment]
> There are two ways that can help with having to define a token on every payload:

thanks, but still need to define on every payloads. 
if goa can handle it in background as of on v1, it would be great.

> See https://goa.design/design/http_mapping/ for detail

It works, so the design will be like:

```
	Method("get", func() {
		Payload(func() {
			Token("token")
			Attribute("positions", MapOf(String, HelloType))
		})
		HTTP(func() {
			Header("token", String)
			GET("/hello")
			Body("positions")
		})
	})
```

**Comment by raphael** [comment]
The second option (creating your own DSL that automatically adds the token) would not require extra code on each request, instead the request would be defined using this custom DSL function (`PayloadWithToken` instead of `Payload`).

**Comment by yogihardi** [comment]
thank you, it would help
