### ISSUE TITLE
Streaming: unable to write error status code

### ISSUE THREAD

**Issue by ghost** [goadesign/goa#3054]
We noticed a change in behavior with https://github.com/goadesign/goa/pull/3001: if no results are streamed back but an error is returned, Goa is unable to write the correct status code.

The new call to `w.Write(nil)` has a [side-effect](https://cs.opensource.google/go/go/+/refs/tags/go1.18.1:src/net/http/server.go;l=118-121) of writing out the "200 OK" status code:
https://github.com/goadesign/goa/blob/7698ee44c9111e26eb0ce4f3b264af44530caf0c/http/codegen/server.go#L498-L506

So for the non-hijacked case, the subsequent call to `encodeError` will be unable to write out the correct status code, printing an error:
```
http: superfluous response.WriteHeader call
```
The rest of the response body can still be written, fortunately, but the status code will be `200`.

**Comment by raphael** [comment]
Hello Jim, would you be able to provide a small repro for this? I believe it might be possible to handle this case by checking whether the stream connection object is `nil` (in which case the connection hasn't been upgraded yet). But a repro would help confirm that this approach would work. Thank you!

**Comment by cubic3d** [comment]
I also stumbled upon this. For testing, I replaced
```
_, err = endpoint(ctx, v)
if err != nil {
	if _, werr := w.Write(nil); werr == http.ErrHijacked {
		// Response writer has been hijacked, do not encode the error
		errhandler(ctx, w, err)
		return
	}
	if err := encodeError(ctx, w, err); err != nil {
		errhandler(ctx, w, err)
	}
	return
}
```
with
```
_, err = endpoint(ctx, v)
if err != nil {
	conn := v.Stream.(*RetrieveServerStream).conn
	if conn != nil {
		// Response writer has been hijacked, do not encode the error
		errhandler(ctx, w, err)
		return
	}
	if err := encodeError(ctx, w, err); err != nil {
		errhandler(ctx, w, err)
	}
	return
}
```
locally in existing API's generated code - seems to solve the issue.

**Comment by raphael** [comment]
That's great - would you be able to put together a PR that made that change? maybe the check can be done inline since `conn` isn't used for anything else:
```go
if v.Stream.(*RetrieveServerStream).conn != nil {
```
This is where the template for this code lives: https://github.com/goadesign/goa/blob/40c28f76e4232c94cedc908bd8bf19c8dd6afcaf/http/codegen/server.go#L498-L508. It should be possible to retrieve the type of the stream using something like `{{ .Method.ServerStream.EndpointStruct }}` (haven't checked - in particular the scope in the template might have to be different).
