### ISSUE TITLE
Is there a way for a "type" to reference some of the fields of another "type".

### ISSUE THREAD

**Issue by v8lab** [goadesign/goa#3214]
Sorry, I just learned goa today. I want to achieve the following effect:

Define a user type and rules

Define a createUserRequest that references the user's partial fields.

**Comment by c-reeder** [comment]
@v8lab 

I think it may be beneficial for you to invert your plan on this.

Rather than trying to use a partial type, you can make one type "extend" another:
```go
var CreateUserPayload = Type("CreateUserPayload", func() {
   Attribute("name", String)
   Attribute("age", Int)
})

var User = Type("User", func() {
    Attribute("id", String, "The ID of this user")
    Extend(CreateUserPayload)
})
```
(I haven't made anything required here, but I expect you'll want to)

Also note that depending on what your app is expecting, an even simpler solution would simply to make some fields required and some optional so that you can choose to omit the ones you only want for _some_ service methods.

**Comment by ElectricCookie** [comment]
New Goa user here too. So excuse me if I'm missing something.

Even though extending is working in this case I find the request quite interesting. I was looking for something like this too.  Extending is always more limited rather than having composability. Say you want to have updates or other operations on the same user object you would be forced to either use the entire object with a required validator (but this might lead to confusion if not all fields are then processed by the API) or to copy the fields, which might lead to mistakes.

A DSL function  that works like ```AttributeRef(Type,"name",func(){// Overrides})``` which would pull the  attribute`name` from `Type`  and add it to the current one would be really clean.

`AttributeRefs(Type,"attribute1","attribute2...)` could pull an entire partial.

Even cleaner would probably be a way to use a view for this type of application.

**Comment by ElectricCookie** [comment]
Update: I was able to achieve a somewhat clean solution by wrapping my Attribute definitions in a function. This function can then be re-used. 

```go
// I declare my types in a package hence uppercase name
var DefaultUserAttributes = func() {
	Attribute("id", String, "Unique user identifier", func() {
		Format("uuid")
	})
	Attribute("firstName", String, "First name of the user", func() {
		MinLength(3)
		MaxLength(64)
		Example("John")
	})
	Attribute("lastName", String, "Last name of the user", func() {
		MinLength(3)
		MaxLength(64)
		Example("Doe")
	})
	Attribute("photoUrl", String, "URL of the user's photo", func() {
		Format("uri")
		Example("https://www.example.com/photo.jpg")
	})
	Attribute("email", String, "Email of the user", func() {
		Format("email")
		Example("john.doe@foo.com")
	})
}

var User = ResultType("User", func() {
  // re use all attributes
  DefaultUserAttributes()
})

// or in a method

Method("updateUser", func() {
  Payload(func() {
    DefaultUserAttributes()
  })
})
```

**Comment by raphael** [comment]
Just a note that the above can be achieved using [Extend](https://pkg.go.dev/goa.design/goa/v3/dsl#Extend) as initially suggested by @c-reeder:
```go
var DefaultUserAttributes = Type("DefaultUserAttributes", func() {
	Attribute("id", String, "Unique user identifier", func() {
		Format("uuid")
	})
	Attribute("firstName", String, "First name of the user", func() {
		MinLength(3)
		MaxLength(64)
		Example("John")
	})
	Attribute("lastName", String, "Last name of the user", func() {
		MinLength(3)
		MaxLength(64)
		Example("Doe")
	})
	Attribute("photoUrl", String, "URL of the user's photo", func() {
		Format("uri")
		Example("https://www.example.com/photo.jpg")
	})
	Attribute("email", String, "Email of the user", func() {
		Format("email")
		Example("john.doe@foo.com")
	})
})

var User = ResultType("User", func() {
  Extend(DefaultUserAttributes)
})

// or in a method

Method("updateUser", func() {
  Payload(DefaultUserAttributes)
})
```
There's also the [Reference](https://pkg.go.dev/goa.design/goa/v3/dsl#Reference) DSL which makes it possible to pick and choose which attribute to reuse.
