### ISSUE TITLE
Optional Boolean attributes with defaults don't distinguish between unset and false

### ISSUE THREAD

**Issue by fg-j** [goadesign/goa#3279]
`design.go`
```go
var CustomType = Type("CustomType", func() {
	Attribute("optional_boolean", Boolean, func() {
		Description("a boolean that's optional, should default to true when unset")
		Default(true)
	})
})
```
Resulting type definition
```go
type CustomType struct {
	// a boolean that's optional, should default to true when unset
	OptionalBoolean bool
}
```

Resulting marshaller
```go
func marshalCustomTypeRequestBodyToMyServiceCustomType(v *CustomTypeRequestBody) *myservice.CustomType {
	if v == nil {
		return nil
	}
	res := &myservice.CustomType{
		OptionalBoolean: v.OptionalBoolean,
	}
	{
		var zero bool // this is "false"
		if res.OptionalBoolean == zero {
			res.OptionalBoolean = true
		}
	}

	return res
}
```

Consequently, users of the generated client will see the value of `OptionalBoolean` set to true _regardless of whether they explicitly set it to false or not_.  Notably, this behaviour only rears its head when the boolean's default is `true`.

**Comment by raphael** [comment]
Can you provide a complete design that reproduces this problem? thank you!

**Comment by fg-j** [comment]
Surely.
Here's a full `design.go`
```go
// This file contains descriptions of services and their methods.
// The methods should be implemented in, e.g. /example/api/service.go.
// Goa will roll up these descriptions and generate the corresponding endpoints.
package design

import (
	. "goa.design/goa/v3/dsl"
	cors "goa.design/plugins/v3/cors/dsl"
)

var _ = API("my-service", func() {
	Title("my-service")
	Description("Services related ")
	Server("my-service", func() {
		Host("localhost", func() {
			URI("http://localhost:8000")
		})
	})
})

var DeduplicateSpecification = Type("DeduplicateSpecification", func() {
	Attribute("matching_names", Boolean, func() {
		Description("de-duplicate when names match")
		Default(true)
	})
})

// Service describes a service
var _ = Service("my-service", func() {
	cors.Origin("*", func() {
		cors.Headers("*")
		cors.Methods("GET", "POST", "PUT", "DELETE", "PATCH")
		cors.Credentials()
	})

	Error("not_found")

	Method("create-dispatch", func() {
		Payload(func() {
			Attribute("name", String, "submission name")
			Attribute("deduplicate_by", DeduplicateSpecification, "how to deduplicate the submission")
		})
		Result(func() {
			Attribute("id", Int, "the submission id")
			Required("id")
		})
		HTTP(func() {
			POST("/submit")
			Response(StatusOK)
		})
	})
})
```

And here's the resulting generated `gen/client/encode_decode.go` with the problematic function:
```go
func marshalMyserviceDeduplicateSpecificationToDeduplicateSpecificationRequestBody(v *myservice.DeduplicateSpecification) *DeduplicateSpecificationRequestBody {
	if v == nil {
		return nil
	}
	res := &DeduplicateSpecificationRequestBody{
		MatchingNames: v.MatchingNames,
	}
	{
		var zero bool
		if res.MatchingNames == zero {
			res.MatchingNames = true // this clobbers user-set false values
		}
	}

	return res
}
```

**Comment by raphael** [comment]
Taking another look at this issue. I wonder what the behavior should be. The idea is that attributes that have a default value should generate fields that are not pointers, so in this case a field that is a `bool` and not a `*bool`. This would be difficult to change because it would break a lot of existing code. So I see two options:
1. Make it an error to specify a default value for boolean fields. The `goa gen` tool would fail in this case with an error message indicating that boolean attributes can't have default values. The obvious drawback is that this behavior would preclude the generation of the transport level code that initializes the field to the default value if missing from the marshaled data.
2. Change the code generation so that the marshaling side (client for payloads, server for results) does not check or set the default value  - only the unmarshaling side would if the field is missing from the marshaled data.

Option 2 is probably preferable?
