### ISSUE TITLE
How to get the native *http.Request from the payload?

### ISSUE THREAD

**Issue by nieshaoyu** [goadesign/goa#3413]

**Comment by raphael** [comment]
There is no direct way to do that by design since that would defeat a bit the point of Goa and the clean separation of layers. Depending on the use case though:
* HTTP Middlewares can be written to handle HTTP transport specific logic
* `SkipRequestBodyEncodeDecode` and/or `SkipResponseBodyEncodeDecode` can be used to get access to the underlying bytes/stream their content.
* Transport specific elements can be added to the request context e.g. via the [PopulateRequestContext](https://github.com/goadesign/goa/blob/v3/http/middleware/request.go#L11) middleware
* As a last resort the request object itself can be added to the context via a middleware so the business logic has access to it (not a great pattern though).
