### ISSUE TITLE
Serve API through WebSocket

### ISSUE THREAD

**Issue by DenisNeustroev** [goadesign/goa#503]
Is it possible to serve API requests through websocket connections?

**Comment by raphael** [comment]
Yes, take a look at https://github.com/goadesign/examples/tree/master/websocket

**Comment by DenisNeustroev** [comment]
OK, How I can implement the same logic (ctx.Left + ctx.Right) for each websocket message? Not only for initial http request in example above?
https://github.com/goadesign/examples/blob/master/adder/operands.go

**Comment by raphael** [comment]
You implement a `websocket.Handler` that does what you need. This gets invoked each time data is received, see https://github.com/goadesign/examples/blob/master/websocket/echo.go#L33-L37

**Comment by DenisNeustroev** [comment]
But I need to serve all api request through one ws connection, with all power of Goa: code generation, validation, docs & etc. Goa gives me any advantages over an ordinary ws handler (=without Goa stack)?

**Comment by raphael** [comment]
Makes sense, today you cannot describe the actual websocket messages in the goa DSL. You can still describe the data structures so validation will work (you'll need to call `Validate` yourself). It would be great to be able to describe the actual messages too though.

**Comment by raphael** [comment]
Going to close this because after thinking more about it what is there today is good enough given how websocket can be used. To recap:

* You can define an endpoint as being a websocket endpoint using the `ws` or `wss` scheme.
* When you do that `goagen` generates the code to implement the websocket endpoint as well as the client code to call it.
* Any data structure defined in the design for example as payload or media type for that endpoint gets properly generated together with validations and JSON struct tags.

What your code has to do then is to handle the unmarshaling and marshaling which should be fairly straightforward. Not having that generated means that different data structures can be used either way which is the more generic use of websocket.
