### ISSUE TITLE
better form-validation

### ISSUE THREAD

**Issue by on99** [goadesign/goa#523]
https://github.com/go-playground/validator  could be a better choice for validation.

I think I can contribute some code if you like the package 😁

**Comment by raphael** [comment]
Thanks for the pointer, I had seen this project before :) I'm not sure where it would fit though. The current validation DSL is heavily inspired from JSONSchema/Swagger which is nice because there is a standard behind and it makes generating the corresponding Swagger natural. Also it doesn't seem great to have to use struct tags in the DSL, there is no struct at the moment. But maybe you're thinking about something else?

**Comment by on99** [comment]
You are right. Users may use this library in their own code, it should not be part of goa.

I need to read the source code again 😢
