### ISSUE TITLE
client: cli URL syntax does not support query params

### ISSUE THREAD

**Issue by bits01** [goadesign/goa#535]
```
Usage:
  cellar-cli show bottle [/bottles/BOTTLEID] [flags]
```

It would be useful for the cli to allow query parameters in the URL syntax. It currently URL encodes it. E.g.

`cellar-cli show bottle /bottles/1?fields=name,id`

**Comment by DhritiShikhar** [comment]
I want to work on this issue. Any pointers on how to start?

**Comment by raphael** [comment]
Awesome! The idea would be to tweak the generated `XXXCommand` struct `Run` methods so that they parse the path command line argument if it was provided.
The code would extract the query string params from the path and set the corresponding `XXXCommand` struct fields.

Here is an example of where this would happen:

[https://github.com/goadesign/goa-cellar/blob/master/tool/cli/commands.go#L529](https://github.com/goadesign/goa-cellar/blob/master/tool/cli/commands.go#L529)

In this example the `Years` command struct field should be set if the `years` query string param is set in the path.

For context: these command structs get created in the generated [RegisterCommands](https://github.com/goadesign/goa-cellar/blob/ef00da9373069a3966c6659e616a60fce39d8f50/tool/cli/commands.go#L184) function that is called by the generated tool `main`. The `RegisterCommands` function also calls the command [RegisterFlags](https://github.com/goadesign/goa-cellar/blob/ef00da9373069a3966c6659e616a60fce39d8f50/tool/cli/commands.go#L546) method that registers the flags that initialize the command fields when using flags rather than the path on the command line.

The code that generate the `Run` method is here:

[https://github.com/goadesign/goa/blob/master/goagen/gen_client/cli_generator.go#L599](https://github.com/goadesign/goa/blob/master/goagen/gen_client/cli_generator.go#L599)

Comparing the template above with the corresponding generated code should help understand how the template variables work.
