### ISSUE TITLE
Proposal: Code regeneration while maintaining business logic

### ISSUE THREAD

**Issue by verdverm** [goadesign/goa#592]
As a developer, I would like my workflow to use the following actions, indifferent to order.

- Edit within the design folder.
- Generate assets with Goa.
- Edit my stubs and business logic.

Proposal:

1. Use `<tag>_start` and `<tag>_end` in place of the `TBD` stubs.
1. Have the generator read the file to extract the inner-stub content
1. Add the inner-content back with the updated AST

Currently

1. The stubbed files are not regenerated
1. The stubbed files are over written

Work around:

1. Rename the current file
1. Regenerate the file
1. Copy the logic back in

(this can be automated with make,bash,sed, etc...)

**Comment by raphael** [comment]
I would like to avoid opening that can of worm :) 

The scaffold files (the service `main.go`, the controller files and the client `main.go`) are generated as a way to help get started. The idea is that it's a *one-time* process. From then on these files are "yours" to maintain and update. `goagen` will *not* override these files if they exist.

This is in contrast with the files generated e.g. in the `app` package which get re-generated entirely (and overwritten) each time. The `app` package is "owned" by goa and you should not put any files in it.

This makes the design/implement cycle seamless. The only things generated by `goagen` that you can edit are the one-time generated scaffold files. Everything else is completely regenerated each time.

**Comment by verdverm** [comment]
How do you feel about only changing the `TBD: implement` to:

```
    // {{ $ctrlName -}}_{{- goify .Name true }}: start_implement

    // Put your logic here

    // {{ $ctrlName -}}_{{- goify .Name true }}: start_implement
```

to facilitate an external tool or process?

**Comment by raphael** [comment]
Sounds good to me.

**Comment by verdverm** [comment]
I can do a PR then, I can also add my Makefile and bash script somewhere

later half sound ok? location? (docs is cool too)

**Comment by raphael** [comment]
Maybe the Makefile could go to the examples repo for now? It's not the perfect place but it's better than an entirely new `tools` repo until we have more of a need for one. 

I have to admit I'm a little hesitant about adding the tags to the main just because in simple apps the generated main is sufficient. Is there a way your script could rely on the current comments?

**Comment by verdverm** [comment]
How did you feel about adding a tag pair to the main file?

**Comment by verdverm** [comment]
Example: https://github.com/goadesign/examples/pull/6

**Comment by verdverm** [comment]
@raphael btw, are you going to be at GopherCon next week?

**Comment by raphael** [comment]
Thanks for the PR! I don't think we should do the same for `main`, for one it is not as valuable (the only changes in `main` between re-generations have to do with adding the two lines it takes to mount new controllers) and for two these comments would have to be removed always even when the generated main is sufficient (for things like examples, demos etc.).

Can you update the PR so that it also works with Go 1.5? (i.e. do not use `{{-` and `-}}`), thank you!

And yes I'll be at Gophercon giving the talk on goa :)
