### ISSUE TITLE
Proposal: Protobuf Generator

### ISSUE THREAD

**Issue by verdverm** [goadesign/goa#595]
Is there an existing generator that outputs the protobuf definition?

How hard would this be in your wisdom?

This would make integrating with other languages and legacy services much easier.
(Because we can generate the other side of PB for clients in other languages)

**Comment by raphael** [comment]
There isn't an existing generator but definitely something that would be great to have. As a prerequisite though it needs to be possible to define types in a more granular way than is possible today (i.e. Int32, UInt64 etc. instead of just `Integer`). The current proposal found in the [roadmap.md](https://github.com/goadesign/goa/blob/master/roadmap.md) file is to extend the `Format` DSL to `Integer` and `Number`. This may end-up being a bit too "heavy" though, it might be good to play with a few variations and see what works.

I'm sure there are other considerations mapping the design to protobuf but doing the above would be a great start :)

**Comment by raphael** [comment]
Closing this as support for Protobuf / gRPC is being built into v2.
