### ISSUE TITLE
Make it possible to provide default values for query string and header params

### ISSUE THREAD

**Issue by Tri125** [goadesign/goa#658]
At the moment we can't specify a default value for params inside a resource or action.

**Comment by bits01** [comment]
I assume URL params implies both path and query params.

**Comment by Tri125** [comment]
I guess I should have called it Action/Resource Params. I'll edit to make it clearer.

**Comment by raphael** [comment]
@bits01 setting default values on path parameters doesn't make a lot of sense because the mux enforces they have values. It might be good to fail actually if defaults are provided for those with a nice error message explaining this. So we're talking about query string parameters and header parameters.
