### ISSUE TITLE
Generate media type struct with fields-pointers

### ISSUE THREAD

**Issue by njspok** [goadesign/goa#750]
When i run `goagen bootsrap` give media type like this
```go
type Unit struct {
	ID *int `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	Name *string `form:"name,omitempty" json:"name,omitempty" xml:"name,omitempty"`
}
```
All fields in this struct is pointers. But in example application "goa-cellar" some fields has primitive type
```go
type Bottle struct {
	Account *AccountTiny `form:"account,omitempty" json:"account,omitempty" xml:"account,omitempty"`
	Href string `form:"href" json:"href" xml:"href"`
	ID int `form:"id" json:"id" xml:"id"`
	Links *BottleLinks `form:"links,omitempty" json:"links,omitempty" xml:"links,omitempty"`
	Name  string       `form:"name" json:"name" xml:"name"`
	Rating   *int   `form:"rating,omitempty" json:"rating,omitempty" xml:"rating,omitempty"`
	Varietal string `form:"varietal" json:"varietal" xml:"varietal"`
	Vineyard string `form:"vineyard" json:"vineyard" xml:"vineyard"`
	Vintage  int    `form:"vintage" json:"vintage" xml:"vintage"`
}
```
If i change struct manually and run `goagen` again my changes overwritten.

**Comment by raphael** [comment]
I would recommend going over http://goa.design/design/overview/ and the other documentation pages if you haven't yet. To answer your questions:
1. `goagen` generates pointers for optional fields. Use `Required` in your design to identify fields that are not optional.
2. You should never ever edit the content of the `app` package. Your code goes in other packages. This helps make clear what happens when you change the design. This is in contrast with code generated in the `main` package which is your code and that `goagen` won't overwrite.

**Comment by njspok** [comment]
Sorry, Im missed this point.
