### ISSUE TITLE
Make logging output of goa-generated CLI tools configurable

### ISSUE THREAD

**Issue by PaulCapestany** [goadesign/goa#851]
As per [this Slack discussion](https://gophers.slack.com/archives/goa/p1478303459000021), if one wants clean, JSON-only output from goa-generated CLI tools, currently there isn't a way to easily enable that. Would be great if this were configurable though.

Here's an example of the current output of running `▸ cellar-cli list bottle --accountID=1` with the [goa-cellar](https://github.com/goadesign/goa-cellar) project:

```
2016/11/05 00:04:32 [INFO] started id=UnEEQDPr GET=http://localhost:8081/cellar/accounts/1/bottles
2016/11/05 00:04:32 [INFO] completed id=UnEEQDPr status=200 time=2.503342ms
[{"account":{"href":"/cellar/accounts/1","id":1,"name":"account 1"},"href":"/cellar/accounts/1/bottles/100","id":100,"links":{"account":{"href":"/cellar/accounts/1","id":1}},"name":"Number 8","rating":4,"varietal":"Merlot","vineyard":"Asti Winery","vintage":2011},{"account":{"href":"/cellar/accounts/1","id":1,"name":"account 1"},"href":"/cellar/accounts/1/bottles/101","id":101,"links":{"account":{"href":"/cellar/accounts/1","id":1}},"name":"Mourvedre","rating":3,"varietal":"Mourvedre","vineyard":"Rideau","vintage":2012},{"account":{"href":"/cellar/accounts/1","id":1,"name":"account 1"},"href":"/cellar/accounts/1/bottles/102","id":102,"links":{"account":{"href":"/cellar/accounts/1","id":1}},"name":"Blue's Cuvee","rating":5,"varietal":"Cabernet Franc with Merlot, Malbec, Cabernet Sauvignon and Syrah","vineyard":"Longoria","vintage":2013}]
```

Ideally we would be able to just get the JSON response, without the `[INFO]` logs.

**Comment by raphael** [comment]
Just a note that the logger outputs to `stderr`. So you can do:
```
cellar-cli list bottle --accountID=1 2>/dev/null
```
to get what you need.

**Comment by maleck13** [comment]
@PaulCapestany @raphael how would we approach implementing this. Should it be quiet by default and require a ```-v``` flag to output logs? Or remain as it is now and add an optional global flag maybe ```--quiet``` ?

**Comment by raphael** [comment]
@maleck13 It should probably be quiet by default although I could be convinced otherwise :) The other question though seems to be how to make it possible to configure the code so that it conditionally logs.

Here is where the logger creation is generated: 
https://github.com/goadesign/goa/blob/master/goagen/gen_client/cli_generator.go#L817-L818
And where it's invoked: https://github.com/goadesign/goa/blob/master/client/client.go#L76 

We shouldn't move the logger to the client struct because that struct is defined in the client package which can be used programmatically in which case the logger is in the context (that's why things are done the way they are today). The simplest thing to do seems to be to add a flag to each command that contains the value of `--verbose` and tweak the code generation to check on this value before creating the logger in the context.

Thank you for looking into this, much appreciated!

**Comment by PaulCapestany** [comment]
@maleck13 @raphael +1 on it being quiet by default. The extra logging output itself isn't actually an issue when it comes to parsing responses, since, as Raphael noted, logs go to `stderr`. I'd say it's more about users' expectations and preventing visual clutter when not needed/wanted (at least for me).
