### ISSUE TITLE
CLI should perform URL encoding

### ISSUE THREAD

**Issue by mark-lb** [goadesign/goa#944]
For example, I attempted to to pass a parameter such as 
`--ip_address 192.168.1.1/24`, e.g. an IP address in CIDR notation.
The framework of course generates a status 404 not found since it sees the slash as an additional path component. The slash should be encoded.

**Comment by raphael** [comment]
Are you using a path parameter for this? query string parameters should be escaped properly.

**Comment by mark-lb** [comment]
@raphael nope, it's a path parameter in this case. In any case, I don't think the CLI user should be the one to worry about the encoding - do you agree?

**Comment by raphael** [comment]
Yes, I'll fix it, thank you!

**Comment by mark-lb** [comment]
@raphael you decided to leave the decoding out of the framework, i.e. the developer needs to decode if necessary. However, noting that this could break some validations. In the example above, `Format("cidr")` will fail

**Comment by raphael** [comment]
Hmm that's a good point. This should be fixed. I'm still hesitant to always decode all path parameters just because in the vast majority of cases it's not necessary. The validation code could attempt to decode on failure though and attempt to validate again on the decoded value, this does mean double validation in these cases though. Alternatively the validation code for certain validators (like the `Format("cidr")` validator) could decode first (because the value being validated always has to be encoded first). Not great either... What would you suggest?

**Comment by mark-lb** [comment]
Perhaps add a Decode function per param, which if Decode(true) does the decode? Kicks in only for path/query params, false by default.
Or add a similar function per resource action?

**Comment by raphael** [comment]
That's an idea, just to be clear you mean in the design right? So something like:

```go
Params(func() {
    Param("ip", String, "IP path parameter", func() {
        Format("cidr")
        URLEncoded()
    })
})
```

**Comment by mark-lb** [comment]
That would be perfect
