### ISSUE TITLE
can use gin (or echo2) as app framework while generate app

### ISSUE THREAD

**Issue by runner-mei** [goadesign/goa#971]
can use gin (or echo2) as app framework while generate app

**Comment by raphael** [comment]
The service mux is a http handler so you can mount it on any web framework that can mount http handlers. Controllers also have a `MuxHandler` method that returns a function which requires the path parameters on top of the HTTP request and response. This function then invokes the handler so that if you mount it on the right path things will work. I have to say though that I am not convinced about the approach. This adds a lot of dependencies for what seems to be little value in the end.
